using System.Text.Json;
using HartsyInference.Audio.Models.SheetSage2;
using Xunit;

namespace HartsyInference.Audio.Tests.Parity;

/// <summary>Gate S1: the C# vocabulary and decode grammar against the released implementation's own output.
///
/// <para>Checked against a committed dump rather than against a reading of the Python, because both are
/// checkpoint facts with no tolerance: the decoder's output projection is exactly as wide as the vocabulary, and
/// an id's meaning is decided purely by which range it lands in. The allow-mask is compared by exact cardinality
/// as well as by probe, so a range that is one token wide in the wrong direction cannot pass.</para>
///
/// <para>Needs no checkpoint, backend or GPU — the fixture is regenerated by
/// <c>tests/python-reference/dump_sheetsage2_reference.py</c>.</para></summary>
public sealed class SheetSage2GrammarParityTests
{
    private static readonly ScoreTokenizer Tok = new();
    private static readonly JsonElement Reference = LoadReference();

    private static JsonElement LoadReference()
    {
        string path = Path.Combine(AppContext.BaseDirectory, "python-reference", "sheetsage2_reference", "grammar.json");
        if (!File.Exists(path))
        {
            // Fall back to the source tree when the fixture was not copied next to the test binary.
            DirectoryInfo? dir = new(AppContext.BaseDirectory);
            while (dir is not null && !Directory.Exists(Path.Combine(dir.FullName, "tests", "python-reference")))
            {
                dir = dir.Parent;
            }
            path = Path.Combine(dir?.FullName ?? ".", "tests", "python-reference", "sheetsage2_reference", "grammar.json");
        }
        return JsonDocument.Parse(File.ReadAllText(path)).RootElement.Clone();
    }

    [Fact]
    public void Vocabulary_MatchesTheReference()
    {
        Assert.Equal(Reference.GetProperty("tokenCount").GetInt32(), Tok.TokenCount);
        Assert.Equal(Reference.GetProperty("chordLabels").GetInt32(), Tok.FullChordLabels.Count);
        Assert.Equal(Reference.GetProperty("meterPairs").GetInt32(), Tok.MeterPairs.Count);
        Assert.Equal(Reference.GetProperty("structureLabels").GetInt32(), ScoreTokenizer.StructureLabels.Length);
        Assert.Equal(Reference.GetProperty("durationTemplates").GetInt32(), ScoreTokenizer.DurationTemplates.Length);
    }

    [Fact]
    public void Ranges_MatchTheReference()
    {
        JsonElement ranges = Reference.GetProperty("ranges");
        Assert.Equal(ranges.GetArrayLength(), Tok.Ranges.Count);
        int i = 0;
        foreach (JsonElement range in ranges.EnumerateArray())
        {
            (string name, int start, int end) = Tok.Ranges[i++];
            Assert.Equal(range.GetProperty("name").GetString(), name);
            Assert.Equal(range.GetProperty("start").GetInt32(), start);
            Assert.Equal(range.GetProperty("end").GetInt32(), end);
        }
    }

    [Fact]
    public void PromptPrefix_MatchesTheReference()
    {
        int[] expected = [.. Reference.GetProperty("promptPrefix").EnumerateArray().Select(e => e.GetInt32())];
        Assert.Equal(expected, ScoreTokenizer.PromptPrefix());
    }

    [Fact]
    public void TokenTypes_MatchTheReference()
    {
        foreach (JsonProperty entry in Reference.GetProperty("tokenTypes").EnumerateObject())
        {
            Assert.Equal(entry.Value.GetString(), Tok.TokenType(int.Parse(entry.Name)));
        }
    }

    /// <summary>Every pinned grammar state, compared by exact allowed-token count and by one probe per field.</summary>
    [Fact]
    public void AllowMasks_MatchTheReference()
    {
        foreach (JsonProperty state in Reference.GetProperty("states").EnumerateObject())
        {
            bool[] allowed = Replay(state.Name);
            JsonElement want = state.Value;
            Assert.Equal(want.GetProperty("allowedCount").GetInt32(), allowed.Count(a => a));
            Assert.Equal(want.GetProperty("eos").GetBoolean(), allowed[ScoreTokenizer.EosToken]);
            foreach ((string field, int start) in Probes())
            {
                Assert.Equal(want.GetProperty(field).GetBoolean(), allowed[start]);
            }
        }
    }

    private (string Field, int Start)[] Probes() =>
    [
        ("subbeat_shift", Tok.SubbeatShiftStart), ("time", Tok.TimeStart), ("meter", Tok.MeterStart),
        ("eighth_position", Tok.EighthPositionStart), ("structure", Tok.StructureStart), ("key", Tok.KeyStart),
        ("majmin_chord", Tok.MajMinChordStart), ("full_chord", Tok.FullChordStart), ("pitch", Tok.PitchStart),
        ("duration", Tok.DurationStart),
    ];

    /// <summary>The same update sequences the dump script drives its states with.</summary>
    private bool[] Replay(string state)
    {
        PromptGrammar grammar = new(Tok);
        foreach ((string field, int offset) in Updates(state))
        {
            grammar.Update(Start(field) + offset);
        }
        return grammar.Allowed();
    }

    private static (string Field, int Offset)[] Updates(string state) => state switch
    {
        "fresh" => [],
        "after_time" => [("time", 10)],
        "after_meter" => [("meter", 3)],
        "after_pitch" => [("pitch", 60)],
        "after_key" => [("key", 1)],
        "after_pitch_duration" => [("key", 1), ("pitch", 60), ("duration", 2)],
        "shift1" => [("subbeat_shift", 0)],
        "shift4" => [.. Enumerable.Repeat(("subbeat_shift", 0), 4)],
        "shift5" => [.. Enumerable.Repeat(("subbeat_shift", 0), 5)],
        "event_then_shift" => [("key", 1), ("subbeat_shift", 1)],
        _ => throw new InvalidOperationException($"The fixture pins a grammar state '{state}' this test cannot replay."),
    };

    private int Start(string field) => field switch
    {
        "subbeat_shift" => Tok.SubbeatShiftStart,
        "time" => Tok.TimeStart,
        "meter" => Tok.MeterStart,
        "eighth_position" => Tok.EighthPositionStart,
        "structure" => Tok.StructureStart,
        "key" => Tok.KeyStart,
        "majmin_chord" => Tok.MajMinChordStart,
        "full_chord" => Tok.FullChordStart,
        "pitch" => Tok.PitchStart,
        "duration" => Tok.DurationStart,
        _ => throw new InvalidOperationException($"Unknown field '{field}'."),
    };
}
