using System.Text.Json;
using HartsyInference.Audio.Models.SheetSage2;
using Xunit;

namespace HartsyInference.Audio.Tests.Parity;

/// <summary>Gate S6: the C# window stitching against the released implementation's own output.
///
/// <para>Stitching is what makes a transcription longer than five minutes one piece of music instead of a
/// sequence of independent readings. Three decisions do it, and all three are pinned here: where a decoded
/// position falls in its window, which of a window's events the window is trusted for, and what is replayed
/// back as the next window's prompt. An off-by-one in the second one duplicates or drops a bar at every seam —
/// silently, correct-looking, and only past the first five minutes of audio — so the fixtures put events exactly
/// on the accepted spans' edges as well as around them.</para>
///
/// <para>Needs no checkpoint, backend or GPU: the fixture's decodes are scripted token streams standing in for
/// what the model would have written. Regenerated by
/// <c>tests/python-reference/dump_sheetsage2_stitch_reference.py</c>.</para></summary>
public sealed class SheetSage2StitchParityTests
{
    private static readonly ScoreTokenizer Tok = new();
    private static readonly ScoreEventCodec Codec = new(Tok);
    private static readonly WindowStitcher Stitcher = new(Tok);
    private static readonly JsonElement Reference = LoadReference();

    private static JsonElement LoadReference()
    {
        string path = Path.Combine(AppContext.BaseDirectory, "python-reference", "sheetsage2_reference", "stitch.json");
        if (!File.Exists(path))
        {
            // Fall back to the source tree when the fixture was not copied next to the test binary.
            DirectoryInfo? dir = new(AppContext.BaseDirectory);
            while (dir is not null && !Directory.Exists(Path.Combine(dir.FullName, "tests", "python-reference")))
            {
                dir = dir.Parent;
            }
            path = Path.Combine(dir?.FullName ?? ".", "tests", "python-reference", "sheetsage2_reference", "stitch.json");
        }
        return JsonDocument.Parse(File.ReadAllText(path)).RootElement.Clone();
    }

    /// <summary>Every pinned time map: its anchors, the tempo it reads off them, and what it says about
    /// positions inside, outside and exactly on those anchors.</summary>
    [Fact]
    public void TimeMaps_MatchTheReference()
    {
        foreach (JsonProperty entry in Reference.GetProperty("timeMaps").EnumerateObject())
        {
            JsonElement want = entry.Value;
            SubbeatTimeMap map = new(Decode(want.GetProperty("stream")), want.GetProperty("targetSeconds").GetDouble());
            Assert.Equal(want.GetProperty("anchorCount").GetInt32(), map.AnchorCount);
            JsonElement period = want.GetProperty("period");
            // The released map keeps no tempo when it has no anchors; it spends the same constant inline.
            double expected = period.ValueKind == JsonValueKind.Null
                ? SubbeatTimeMap.DefaultSubbeatSeconds : period.GetDouble();
            Assert.Equal(expected, map.SubbeatSeconds);
            foreach (JsonElement probe in want.GetProperty("probes").EnumerateArray())
            {
                Assert.Equal(probe.GetProperty("seconds").GetDouble(), map.Seconds(probe.GetProperty("step").GetInt32()));
            }
        }
    }

    /// <summary>Every pinned overlap, token for token. The prompt is compared exactly because the decoder reads
    /// it as its own earlier output: a prompt that differs by one token is a different reading of the song.</summary>
    [Fact]
    public void Overlaps_MatchTheReference()
    {
        foreach (JsonProperty entry in Reference.GetProperty("prefixes").EnumerateObject())
        {
            JsonElement want = entry.Value;
            SheetSage2Window window = WindowAt(want.GetProperty("start").GetDouble(), want.GetProperty("prefixEnd").GetDouble());
            (List<int>? tokens, int position) = Stitcher.OverlapPrefix(Stitched(want), window);
            Assert.Equal(want.GetProperty("base").GetInt32(), position);
            JsonElement expected = want.GetProperty("tokens");
            if (expected.ValueKind == JsonValueKind.Null) Assert.Null(tokens);
            else Assert.Equal(Ints(expected), tokens);
        }
    }

    /// <summary>Events sitting exactly on an accepted span's edges, and a tolerance to either side of them.
    ///
    /// <para>The tolerance is asymmetric: a window takes an event a tolerance BEFORE its span but hands one a
    /// tolerance before its END to the next window. That is what makes the spans tile the clip exactly once, and
    /// it is the single most inviting thing in this port to "clean up" into a symmetric comparison.</para></summary>
    [Fact]
    public void AcceptedSpans_MatchTheReferenceAtTheirEdges()
    {
        foreach (JsonProperty entry in Reference.GetProperty("boundaries").EnumerateObject())
        {
            JsonElement want = entry.Value;
            List<ScoreEvent> decoded = Decode(want.GetProperty("stream"));
            SheetSage2Window window = new(
                Start: want.GetProperty("start").GetDouble(),
                End: want.GetProperty("start").GetDouble() + SlidingWindowPlan.WindowSeconds,
                AcceptStart: want.GetProperty("acceptStart").GetDouble(),
                AcceptEnd: want.GetProperty("acceptEnd").GetDouble(),
                PrefixEnd: want.GetProperty("acceptStart").GetDouble(),
                GenerationStop: null);
            List<StitchedScoreEvent> accepted = Stitcher.WindowEvents(decoded, new SubbeatTimeMap(decoded), window,
                want.GetProperty("duration").GetDouble(), want.GetProperty("base").GetInt32());
            AssertAccepted(entry.Name, want.GetProperty("accepted"), accepted);
        }
    }

    /// <summary>Whole clips, window by window, driven through the ported plan rather than the fixture's copy of
    /// it — so the plan, the prompt it asks for and the events it accepts are checked as one pipeline.</summary>
    [Fact]
    public void Clips_MatchTheReference()
    {
        foreach (JsonProperty entry in Reference.GetProperty("clips").EnumerateObject())
        {
            JsonElement clip = entry.Value;
            double duration = clip.GetProperty("duration").GetDouble();
            IReadOnlyList<SheetSage2Window> plan = SlidingWindowPlan.For(duration);
            JsonElement windows = clip.GetProperty("windows");
            Assert.Equal(windows.GetArrayLength(), plan.Count);

            List<StitchedScoreEvent> stitched = [];
            int index = 0;
            foreach (JsonElement want in windows.EnumerateArray())
            {
                SheetSage2Window window = plan[index];
                string where = $"{entry.Name} window {index++}";
                Assert.Equal(want.GetProperty("start").GetDouble(), window.Start);
                Assert.Equal(want.GetProperty("acceptStart").GetDouble(), window.AcceptStart);
                Assert.Equal(want.GetProperty("acceptEnd").GetDouble(), window.AcceptEnd);
                Assert.Equal(want.GetProperty("prefixEnd").GetDouble(), window.PrefixEnd);

                (List<int>? prompt, int position) = Stitcher.OverlapPrefix(stitched, window);
                JsonElement expected = want.GetProperty("prefixTokens");
                if (expected.ValueKind == JsonValueKind.Null) Assert.Null(prompt);
                else Assert.Equal(Ints(expected), prompt);
                Assert.Equal(want.GetProperty("base").GetInt32(), position);

                List<ScoreEvent> decoded = Decode(want.GetProperty("stream"));
                SubbeatTimeMap times = new(decoded);
                Assert.Equal(want.GetProperty("anchorCount").GetInt32(), times.AnchorCount);
                List<StitchedScoreEvent> accepted = Stitcher.WindowEvents(decoded, times, window, duration, position);
                AssertAccepted(where, want.GetProperty("accepted"), accepted);
                stitched.AddRange(accepted);
            }
        }
    }

    /// <summary>The property the seams exist to preserve, asserted on the port's own output rather than on the
    /// fixture: across a whole clip no position is transcribed twice and no event lands outside the audio.
    ///
    /// <para>These scripted decodes also come out in order, which is asserted because it is cheap — but nothing
    /// guarantees it in general, since a window's time map need not be monotonic. That is why the released driver
    /// sorts the finished stream, and a fixture that made a map run backwards would belong there, not here.</para></summary>
    [Fact]
    public void AClipsSeams_TakeEveryMomentExactlyOnce()
    {
        foreach (JsonProperty entry in Reference.GetProperty("clips").EnumerateObject())
        {
            JsonElement clip = entry.Value;
            double duration = clip.GetProperty("duration").GetDouble();
            IReadOnlyList<SheetSage2Window> plan = SlidingWindowPlan.For(duration);
            List<StitchedScoreEvent> stitched = [];
            int index = 0;
            foreach (JsonElement want in clip.GetProperty("windows").EnumerateArray())
            {
                SheetSage2Window window = plan[index++];
                (_, int position) = Stitcher.OverlapPrefix(stitched, window);
                List<ScoreEvent> decoded = Decode(want.GetProperty("stream"));
                stitched.AddRange(Stitcher.WindowEvents(decoded, new SubbeatTimeMap(decoded), window, duration, position));
            }
            HashSet<int> positions = [];
            for (int i = 0; i < stitched.Count; i++)
            {
                Assert.True(stitched[i].Seconds >= 0 && stitched[i].Seconds < duration,
                    $"{entry.Name}: an event at {stitched[i].Seconds} is outside a clip of {duration}");
                Assert.True(positions.Add(stitched[i].GlobalSubbeat),
                    $"{entry.Name}: position {stitched[i].GlobalSubbeat} was transcribed twice");
                if (i > 0)
                {
                    Assert.True(stitched[i].Seconds >= stitched[i - 1].Seconds,
                        $"{entry.Name}: the stream walks back at {stitched[i].Seconds}");
                }
            }
        }
    }

    /// <summary>A window that decoded nothing usable gets no prompt, which is the one case where the next window
    /// legitimately starts its reading over.</summary>
    [Fact]
    public void AnOverlapWithNothingToReplay_HasNoPrompt()
    {
        SheetSage2Window window = WindowAt(100.0, 200.0);
        Assert.Equal((null, 0), Stitcher.OverlapPrefix([], window));
    }

    /// <summary>An opening event whose bar position is present but empty inherits no time signature.
    ///
    /// <para>Built by hand rather than dumped, because the released decode cannot write the input: a field only
    /// exists once a token has landed in it. The reference's guard is written against the field's CONTENTS, not
    /// against whether it is there, so this is the behaviour it would have — and the only thing keeping a bare
    /// time signature, claiming a downbeat the window never wrote, out of the prompt.</para></summary>
    [Fact]
    public void AnOpeningEventWithAnEmptyBarPosition_InheritsNoMeter()
    {
        ScoreEvent earlier = new()
        {
            Subbeat = 0,
            TokensByField = new(StringComparer.Ordinal)
            {
                ["rhythm"] = [Tok.MeterStart + 20, Tok.EighthPositionStart + 3],
            },
        };
        ScoreEvent opening = new()
        {
            Subbeat = 20,
            TokensByField = new(StringComparer.Ordinal)
            {
                ["timestamp"] = [Tok.TimeStart + 250],
                ["rhythm"] = [],
            },
        };
        List<StitchedScoreEvent> stitched =
        [
            new() { Source = earlier, Seconds = 50.0, GlobalSubbeat = 400 },
            new() { Source = opening, Seconds = 102.5, GlobalSubbeat = 820 },
        ];
        (List<int>? tokens, int position) = Stitcher.OverlapPrefix(stitched, WindowAt(100.0, 200.0));
        Assert.Equal(820, position);
        Assert.DoesNotContain(tokens!, token => token >= Tok.MeterStart && token < Tok.MeterEnd);
    }

    /// <summary>A window whose events all sit outside the clip keeps none of them, whatever its span says.</summary>
    [Fact]
    public void EventsPastTheEndOfTheClip_AreNotAccepted()
    {
        List<ScoreEvent> decoded = Decode(Reference.GetProperty("boundaries").GetProperty("acceptStartOnEvent")
            .GetProperty("stream"));
        SheetSage2Window window = new(100.0, 400.0, 0.0, 1000.0, 0.0, null);
        Assert.Empty(Stitcher.WindowEvents(decoded, new SubbeatTimeMap(decoded), window, 100.0));
    }

    [Fact]
    public void ANullTokenizer_IsRefusedAtConstruction() => Assert.Throws<ArgumentNullException>(() => new WindowStitcher(null!));

    [Fact]
    public void NullArguments_AreRefused()
    {
        SheetSage2Window window = WindowAt(0.0, 100.0);
        Assert.Throws<ArgumentNullException>(() => new SubbeatTimeMap(null!));
        Assert.Throws<ArgumentNullException>(() => Stitcher.WindowEvents(null!, new SubbeatTimeMap([]), window, 100.0));
        Assert.Throws<ArgumentNullException>(() => Stitcher.WindowEvents([], null!, window, 100.0));
        Assert.Throws<ArgumentNullException>(() => Stitcher.OverlapPrefix(null!, window));
    }

    private static void AssertAccepted(string where, JsonElement want, IReadOnlyList<StitchedScoreEvent> got)
    {
        Assert.Equal(want.GetArrayLength(), got.Count);
        int i = 0;
        foreach (JsonElement expected in want.EnumerateArray())
        {
            StitchedScoreEvent actual = got[i];
            string at = $"{where} event {i++}";
            Assert.Equal(expected.GetProperty("subbeat").GetInt32(), actual.Subbeat);
            Assert.Equal(expected.GetProperty("globalSubbeat").GetInt32(), actual.GlobalSubbeat);
            Assert.True(expected.GetProperty("seconds").GetDouble() == actual.Seconds,
                $"{at}: placed at {actual.Seconds}, not {expected.GetProperty("seconds").GetDouble()}");
            JsonElement timestamp = expected.GetProperty("timestamp");
            if (timestamp.ValueKind == JsonValueKind.Null) Assert.Null(actual.Timestamp);
            else Assert.Equal(timestamp.GetDouble(), actual.Timestamp!.Value);
            JsonElement ends = expected.GetProperty("noteEnds");
            Assert.Equal(ends.GetArrayLength(), actual.Melody?.Count ?? 0);
            int n = 0;
            foreach (JsonElement end in ends.EnumerateArray())
            {
                Assert.Equal(end.GetDouble(), actual.Melody![n++].EndSeconds);
            }
        }
    }

    /// <summary>A window shaped like the plan's, for a fixture that pins only where it starts and where its
    /// replayed prompt ends.</summary>
    private static SheetSage2Window WindowAt(double start, double prefixEnd) => new(
        Start: start,
        End: start + SlidingWindowPlan.WindowSeconds,
        AcceptStart: prefixEnd,
        AcceptEnd: start + SlidingWindowPlan.WindowSeconds - SlidingWindowPlan.LookaheadSeconds,
        PrefixEnd: prefixEnd,
        GenerationStop: SlidingWindowPlan.WindowSeconds - SlidingWindowPlan.LookaheadSeconds);

    private static List<ScoreEvent> Decode(JsonElement stream) => Codec.DecodeSequence(Ints(stream));

    /// <summary>The fixture's hand-built accepted events: real decoded tokens, placed where the case wants them.</summary>
    private static List<StitchedScoreEvent> Stitched(JsonElement want)
    {
        JsonElement stream = want.GetProperty("stream");
        if (stream.ValueKind == JsonValueKind.Null) return [];
        List<ScoreEvent> decoded = Decode(stream);
        double[] seconds = [.. want.GetProperty("seconds").EnumerateArray().Select(e => e.GetDouble())];
        int[] positions = [.. want.GetProperty("globalSubbeats").EnumerateArray().Select(e => e.GetInt32())];
        Assert.Equal(decoded.Count, seconds.Length);
        Assert.Equal(decoded.Count, positions.Length);
        List<StitchedScoreEvent> stitched = new(decoded.Count);
        for (int i = 0; i < decoded.Count; i++)
        {
            stitched.Add(new StitchedScoreEvent
            {
                Source = decoded[i],
                Seconds = seconds[i],
                GlobalSubbeat = positions[i],
            });
        }
        return stitched;
    }

    private static int[] Ints(JsonElement array) => [.. array.EnumerateArray().Select(e => e.GetInt32())];
}
