using System.Text.Json;
using System.Text.RegularExpressions;
using HartsyInference.Audio.Models.SheetSage2;
using Xunit;

namespace HartsyInference.Audio.Tests.Parity;

/// <summary>Gate S7: the C# ABC serializer against the released implementation's own output, character for character.
///
/// <para>String-exact rather than tolerant, because the output is a dialect an external validator parses. A bar
/// written as two tied halves instead of one note, or a rest bar written out instead of folded into <c>Z</c>,
/// is the same music and a different document.</para>
///
/// <para>The fixture's event streams are hand-built. A real transcription is four-four throughout, never carries
/// a pickup, never changes key mid-bar and never uses a flat-root slash chord, so it would leave most of the
/// serializer untested; each case here is aimed at one path that a decoded song would not reach.</para>
///
/// <para>Needs no checkpoint, backend or GPU — the fixture is regenerated by
/// <c>tests/python-reference/dump_sheetsage2_abc_reference.py</c>.</para></summary>
public sealed class SheetSage2AbcParityTests
{
    private static readonly JsonElement Reference = LoadReference();

    private static readonly Regex HeaderLine = new("^[A-Za-z]:", RegexOptions.None, TimeSpan.FromSeconds(2));

    private static readonly Regex QuotedText = new("\"[^\"]*\"", RegexOptions.None, TimeSpan.FromSeconds(2));

    public static TheoryData<string> CaseNames()
    {
        TheoryData<string> names = [];
        foreach (JsonProperty entry in Reference.GetProperty("cases").EnumerateObject())
        {
            names.Add(entry.Name);
        }
        return names;
    }

    private static JsonElement LoadReference()
    {
        string path = Path.Combine(AppContext.BaseDirectory, "python-reference", "sheetsage2_reference", "abc.json");
        if (!File.Exists(path))
        {
            // Fall back to the source tree when the fixture was not copied next to the test binary.
            DirectoryInfo? dir = new(AppContext.BaseDirectory);
            while (dir is not null && !Directory.Exists(Path.Combine(dir.FullName, "tests", "python-reference")))
            {
                dir = dir.Parent;
            }
            path = Path.Combine(dir?.FullName ?? ".", "tests", "python-reference", "sheetsage2_reference", "abc.json");
        }
        return JsonDocument.Parse(File.ReadAllText(path)).RootElement.Clone();
    }

    [Fact]
    public void GridConstants_MatchTheReference()
    {
        int subbeatDivision = AbcSerializer.SubbeatDivision;
        Assert.Equal(Reference.GetProperty("subbeatDivision").GetInt32(), subbeatDivision);
        Assert.Equal([.. Reference.GetProperty("voiceIds").EnumerateArray().Select(e => e.GetString()!)],
            AbcSerializer.VoiceIds);
    }

    /// <summary>The whole pipeline, both modes, compared as text.</summary>
    [Theory]
    [MemberData(nameof(CaseNames))]
    public void RenderedAbc_MatchesTheReference(string name)
    {
        JsonElement want = Reference.GetProperty("cases").GetProperty(name);
        List<TimedScoreEvent> events = ReadEvents(want.GetProperty("events"));
        double duration = want.GetProperty("duration").GetDouble();
        Assert.Equal(want.GetProperty("melodyOnly").GetString(), AbcSerializer.EventsToAbc(events, duration));
        Assert.Equal(want.GetProperty("full").GetString(),
            AbcSerializer.EventsToAbc(events, duration, melodyOnly: false));
    }

    /// <summary>Gate S7b: melody mode is not a chord strip.
    ///
    /// <para>A downstream UI wanted to render once and hide the chords client-side. It cannot. Chords change how
    /// the rest of the score is spelled, three ways: a chord change inside a sustained note splits it into tied
    /// pieces, a bar carrying a chord symbol cannot be folded into a multi-bar <c>Z</c> rest, and the same
    /// applies within a bar to a rest that a chord change cuts in two. Whether any case is affected depends
    /// entirely on where the chords land, so the fixture pins the answer per case and this asserts the port
    /// reproduces it either way — including the cases where the two DO coincide, since a port that always
    /// diverged would otherwise look correct.</para></summary>
    [Theory]
    [MemberData(nameof(CaseNames))]
    public void StrippingChordsOutOfTheFullRendering_MatchesTheReference(string name)
    {
        JsonElement want = Reference.GetProperty("cases").GetProperty(name);
        List<TimedScoreEvent> events = ReadEvents(want.GetProperty("events"));
        double duration = want.GetProperty("duration").GetDouble();
        string melodyOnly = AbcSerializer.EventsToAbc(events, duration);
        string stripped = StripChords(AbcSerializer.EventsToAbc(events, duration, melodyOnly: false));
        Assert.Equal(want.GetProperty("strippedFull").GetString(), stripped);
        Assert.Equal(want.GetProperty("strippedFullEqualsMelodyOnly").GetBoolean(), stripped == melodyOnly);
    }

    /// <summary>The strongest single statement this gate makes: 55 events the released model really produced
    /// from thirty seconds of solo piano, rendered both ways, character for character.
    ///
    /// <para>Kept as a named test on top of the theory above so that dropping the case from the fixture fails
    /// loudly instead of quietly shrinking the gate. It is one window, so it says nothing about the stitching
    /// seam; what it does say is that the port handles the event shapes the model actually emits — events
    /// carrying a bar position but no meter, a chord track opening on no-chord, a key change, both tracks and
    /// multi-bar rests — rather than the ones a hand-built stream imagines.</para></summary>
    [Fact]
    public void ARealTranscription_RendersExactly()
    {
        JsonElement want = Reference.GetProperty("cases").GetProperty("real_piano30");
        List<TimedScoreEvent> events = ReadEvents(want.GetProperty("events"));
        double duration = want.GetProperty("duration").GetDouble();
        Assert.Equal(55, events.Count);
        Assert.Equal(want.GetProperty("melodyOnly").GetString(), AbcSerializer.EventsToAbc(events, duration));
        Assert.Equal(want.GetProperty("full").GetString(),
            AbcSerializer.EventsToAbc(events, duration, melodyOnly: false));
    }

    /// <summary>At least one pinned case has to actually diverge, or the gate above proves nothing.</summary>
    [Fact]
    public void AtLeastOneCase_DivergesUnderAChordStrip()
    {
        int diverging = 0;
        foreach (JsonProperty entry in Reference.GetProperty("cases").EnumerateObject())
        {
            if (!entry.Value.GetProperty("strippedFullEqualsMelodyOnly").GetBoolean()) diverging++;
        }
        Assert.True(diverging > 0, "the fixture no longer covers a case where melody mode is not a chord strip");
    }

    /// <summary>The inferred bar table and its diagnostics, which never reach the ABC text and so cannot be
    /// caught by comparing it — a bar wrongly flagged as a pickup renders identically until it does not.</summary>
    [Theory]
    [MemberData(nameof(CaseNames))]
    public void ResolvedScore_MatchesTheReference(string name)
    {
        JsonElement want = Reference.GetProperty("cases").GetProperty(name).GetProperty("score");
        JsonElement caseData = Reference.GetProperty("cases").GetProperty(name);
        RebuiltAbcScore score = AbcSerializer.BuildScore(ReadEvents(caseData.GetProperty("events")),
            caseData.GetProperty("duration").GetDouble(), melodyOnly: false);

        Assert.Equal(want.GetProperty("beatCount").GetInt32(), score.Beats.Count);
        Assert.Equal(want.GetProperty("subbeatCount").GetInt32(), score.SubbeatTimes.Length);
        Assert.Equal(want.GetProperty("unitDenominator").GetInt32(), AbcSerializer.AbcUnitDenominator(score));
        Assert.Equal(want.GetProperty("tempo").GetDouble(), AbcSerializer.EstimateTempo(score), 9);
        Assert.Equal([.. want.GetProperty("diagnostics").EnumerateArray().Select(e => e.GetString()!)],
            score.Diagnostics);

        JsonElement measures = want.GetProperty("measures");
        Assert.Equal(measures.GetArrayLength(), score.Measures.Count);
        int index = 0;
        foreach (JsonElement expected in measures.EnumerateArray())
        {
            Measure got = score.Measures[index++];
            Assert.Equal(expected.GetProperty("index").GetInt32(), got.Index);
            Assert.Equal(expected.GetProperty("startBeat").GetInt32(), got.StartBeat);
            Assert.Equal(expected.GetProperty("endBeat").GetInt32(), got.EndBeat);
            Assert.Equal(expected.GetProperty("numerator").GetInt32(), got.Numerator);
            Assert.Equal(expected.GetProperty("denominator").GetInt32(), got.Denominator);
            Assert.Equal(expected.GetProperty("pickup").GetBoolean(), got.Pickup);
            Assert.Equal(expected.GetProperty("partial").GetBoolean(), got.Partial);
            Assert.Equal(expected.GetProperty("inferred").GetBoolean(), got.Inferred);
            AssertNullableInt(expected.GetProperty("notatedNumerator"), got.NotatedNumerator);
            AssertNullableInt(expected.GetProperty("notatedDenominator"), got.NotatedDenominator);
            Assert.Equal(expected.GetProperty("padBefore").GetBoolean(), got.PadBefore);
            Assert.Equal(expected.GetProperty("abcNumerator").GetInt32(), got.AbcNumerator);
            Assert.Equal(expected.GetProperty("abcDenominator").GetInt32(), got.AbcDenominator);
        }

        AssertDoubles(want.GetProperty("subbeatTimes"), score.SubbeatTimes);
        AssertDoubles(want.GetProperty("subbeatQuarters"), score.SubbeatQuarters);
        Assert.Equal(ExpandInts(want.GetProperty("subbeatDenominators")), score.SubbeatDenominators);
        Assert.Equal(ExpandStrings(want.GetProperty("keyArr")), score.KeyArr);
        Assert.Equal(ExpandStrings(want.GetProperty("chordArr")), score.ChordArr);
        foreach (JsonProperty voice in want.GetProperty("voiceArrs").EnumerateObject())
        {
            Assert.Equal(ExpandInts(voice.Value), score.VoiceArrs[voice.Name]);
        }

        JsonElement structure = want.GetProperty("structureEvents");
        Assert.Equal(structure.GetArrayLength(), score.StructureEvents.Count);
        int event_ = 0;
        foreach (JsonElement expected in structure.EnumerateArray())
        {
            (int subbeat, string label) = score.StructureEvents[event_++];
            Assert.Equal(expected[0].GetInt32(), subbeat);
            Assert.Equal(expected[1].GetString(), label);
        }
    }

    /// <summary>Melody mode zeroes the chord track rather than skipping the chord pass, so every subbeat is the
    /// no-chord label and no chord symbol can survive into the text.</summary>
    [Fact]
    public void MelodyMode_LeavesNoChordOnEverySubbeat()
    {
        JsonElement caseData = Reference.GetProperty("cases").GetProperty("chord_spellings");
        RebuiltAbcScore score = AbcSerializer.BuildScore(ReadEvents(caseData.GetProperty("events")),
            caseData.GetProperty("duration").GetDouble());
        Assert.All(score.ChordArr, chord => Assert.Equal("N", chord));
    }

    [Fact]
    public void ChordSymbols_MatchTheReference()
    {
        foreach (JsonProperty entry in Reference.GetProperty("chordSymbols").EnumerateObject())
        {
            string? expected = entry.Value.ValueKind == JsonValueKind.Null ? null : entry.Value.GetString();
            Assert.Equal(expected, AbcPitchSpelling.ChordSymbolToAbc(entry.Name));
        }
    }

    /// <summary>A chord the serializer cannot spell is refused, never rewritten as something close: a seventh
    /// silently flattened to a major triad is a wrong transcription nothing downstream can detect.</summary>
    [Fact]
    public void ChordFailures_MatchTheReference()
    {
        foreach (JsonProperty entry in Reference.GetProperty("chordFailures").EnumerateObject())
        {
            Assert.Equal("ChordSymbolError", entry.Value.GetString());
            Assert.Throws<ChordSymbolException>(() => AbcPitchSpelling.ChordSymbolToAbc(entry.Name));
        }
    }

    [Fact]
    public void KeySymbols_MatchTheReference()
    {
        foreach (JsonProperty entry in Reference.GetProperty("keySymbols").EnumerateObject())
        {
            Assert.Equal(entry.Value.GetString(), AbcPitchSpelling.KeySymbolToAbc(entry.Name));
        }
    }

    /// <summary>Including which exception each failure raises: the reference reports an unspellable key root as a
    /// chord-symbol error, because the root parser is shared, and a port that tidied that up would be a
    /// behaviour change for any caller catching the narrower type.</summary>
    [Fact]
    public void KeyFailures_MatchTheReference()
    {
        foreach (JsonProperty entry in Reference.GetProperty("keyFailures").EnumerateObject())
        {
            Exception error = Assert.ThrowsAny<AbcRebuildException>(
                () => AbcPitchSpelling.KeySymbolToAbc(entry.Name));
            string expected = entry.Value.GetString() == "ChordSymbolError" ? "ChordSymbolException" : "AbcRebuildException";
            Assert.Equal(expected, error.GetType().Name);
        }
    }

    [Fact]
    public void KeyAccidentals_MatchTheReference()
    {
        foreach (JsonProperty entry in Reference.GetProperty("keyAccidentals").EnumerateObject())
        {
            Assert.Equal([.. entry.Value.EnumerateArray().Select(e => e.GetInt32())],
                AbcPitchSpelling.GetKeyAccidentals(entry.Name));
        }
    }

    /// <summary>Every pitch class over three octaves under seventeen key signatures. This is what pins the
    /// key-relative spelling table, including the double accidentals remote keys need and the Cb/B# spellings
    /// that cross the MIDI octave boundary without their note letter crossing it.</summary>
    [Fact]
    public void NoteSpellings_MatchTheReference()
    {
        foreach (JsonProperty entry in Reference.GetProperty("noteSpellings").EnumerateObject())
        {
            int[] accidentals = AbcPitchSpelling.GetKeyAccidentals(entry.Name);
            int note = 48;
            foreach (JsonElement expected in entry.Value.EnumerateArray())
            {
                Assert.Equal(expected.GetString(), AbcPitchSpelling.NoteToAbc(note++, accidentals, []));
            }
        }
    }

    /// <summary>The same bar state carried across notes, which is what suppresses a repeated accidental — both
    /// parsers hold an accidental to the next barline, in every octave.</summary>
    [Fact]
    public void RunningBarAccidentals_MatchTheReference()
    {
        int[] accidentals = AbcPitchSpelling.GetKeyAccidentals("Eb");
        Dictionary<int, int> measureAccidentals = [];
        int index = 0;
        int[] notes = [63, 75, 62, 74, 63, 60, 61];
        foreach (JsonElement expected in Reference.GetProperty("noteSpellingsRunning").EnumerateArray())
        {
            Assert.Equal(expected.GetString(), AbcPitchSpelling.NoteToAbc(notes[index++], accidentals, measureAccidentals));
        }
        Assert.Equal(notes.Length, index);
    }

    [Fact]
    public void DurationSplits_MatchTheReference()
    {
        foreach (JsonProperty entry in Reference.GetProperty("durationSplits").EnumerateObject())
        {
            Assert.Equal([.. entry.Value.EnumerateArray().Select(e => e.GetInt32())],
                AbcSerializer.SplitDurationUnits(int.Parse(entry.Name)));
        }
        Assert.Throws<AbcRebuildException>(() => AbcSerializer.SplitDurationUnits(0));
        Assert.Throws<AbcRebuildException>(() => AbcSerializer.SplitDurationUnits(-4));
    }

    /// <summary>Which rendered bars fold into ABC's <c>Z</c>. A chord symbol or an inline key change pins a bar
    /// in place, which is the mechanism behind half of the melody/full divergence above.</summary>
    [Fact]
    public void FullRestCompression_MatchesTheReference()
    {
        foreach (JsonProperty entry in Reference.GetProperty("compressibleFullRest").EnumerateObject())
        {
            Assert.Equal(entry.Value.GetBoolean(), AbcSerializer.IsCompressibleFullRest(entry.Name));
        }
    }

    [Fact]
    public void AGridWithFewerThanTwoBeats_IsRefused()
    {
        List<TimedScoreEvent> events =
            [Beat(0.0, 4, 4, 0, key: "C:major"), new TimedScoreEvent { Time = 1.0, Chord = "C:maj" }];
        Assert.Throws<BeatGridException>(() => AbcSerializer.EventsToAbc(events, 2.0));
    }

    [Fact]
    public void BeatsThatDoNotAdvance_AreRefused()
    {
        List<TimedScoreEvent> events = [Beat(0.0, 4, 4, 0, key: "C:major"), Beat(0.0, 4, 4, 2)];
        Assert.Throws<BeatGridException>(() => AbcSerializer.EventsToAbc(events, 2.0));
    }

    /// <summary>A beat position the declared meter has no room for. The grid is what every later stage indexes,
    /// so a position outside it has to fail here rather than land on the wrong bar.</summary>
    [Fact]
    public void ABeatPositionOutsideItsOwnMeter_IsRefused()
    {
        List<TimedScoreEvent> events = [Beat(0.0, 3, 4, 0, key: "C:major"), Beat(0.5, 3, 4, 6)];
        Assert.Throws<BeatGridException>(() => AbcSerializer.EventsToAbc(events, 2.0));
        // 8ths that do not divide into whole beats have no place on the grid either.
        List<TimedScoreEvent> offGrid = [Beat(0.0, 4, 4, 0, key: "C:major"), Beat(0.5, 4, 4, 1)];
        Assert.Throws<BeatGridException>(() => AbcSerializer.EventsToAbc(offGrid, 2.0));
    }

    [Fact]
    public void AScoreWithNoKey_IsRefused()
    {
        List<TimedScoreEvent> events = [Beat(0.0, 4, 4, 0), Beat(0.5, 4, 4, 2), Beat(1.0, 4, 4, 4)];
        Assert.Throws<AbcRebuildException>(() => AbcSerializer.EventsToAbc(events, 1.5));
    }

    /// <summary>The reference indexes a two-element tuple for the voice, so a third track raises an IndexError
    /// and a negative one silently lands on the instrumental line. This refuses both — a deliberate divergence,
    /// since a note quietly moved to the wrong voice is the worst available outcome.</summary>
    [Fact]
    public void AMelodyNoteOnANonexistentTrack_IsRefused()
    {
        foreach (int track in (int[])[2, -1])
        {
            List<TimedScoreEvent> events =
            [
                Beat(0.0, 4, 4, 0, key: "C:major", melody: [new TimedScoreNote(60, track, 0.5)]),
                Beat(0.5, 4, 4, 2), Beat(1.0, 4, 4, 4),
            ];
            Assert.Throws<MelodyVoiceException>(() => AbcSerializer.EventsToAbc(events, 1.5));
        }
    }

    /// <summary>Notes that collide on one voice are trimmed, never refused.
    ///
    /// <para>The trim pass runs before quantization and leaves every span on a voice disjoint, so the melody
    /// array's own overlap guard cannot be reached through <see cref="AbcSerializer.EventsToAbc"/> at all — it
    /// defends a score assembled by hand. Two notes sharing an onset lose the one the sort puts first, which is
    /// the lower pitch: it is cut to zero length against the other's start and dropped. The
    /// <c>overlapping_notes</c> case pins the resulting voice array, so this only has to establish that nothing
    /// is refused.</para></summary>
    [Fact]
    public void NotesThatCollideOnOneVoice_AreTrimmedRatherThanRefused()
    {
        List<TimedScoreEvent> events =
        [
            Beat(0.0, 4, 4, 0, key: "C:major",
                melody: [new TimedScoreNote(60, 0, 1.0), new TimedScoreNote(64, 0, 1.0)]),
            Beat(0.5, 4, 4, 2), Beat(1.0, 4, 4, 4), Beat(1.5, 4, 4, 6), Beat(2.0, 4, 4, 0),
        ];
        RebuiltAbcScore score = AbcSerializer.BuildScore(events, 2.5);
        // 64 * 2 + 3 is the onset code for the surviving pitch; the lower note left nothing behind.
        Assert.Equal((64 * 2) + 3, score.VoiceArrs["Vocal"][0]);
        Assert.DoesNotContain((60 * 2) + 3, score.VoiceArrs["Vocal"]);
    }

    /// <summary>A beat period below the decoder's own 100 Hz timestamp resolution. The reference walks its
    /// grid-extension loop one beat at a time with no bound and would synthesize millions of them; this refuses,
    /// a deliberate divergence.</summary>
    [Fact]
    public void ABeatPeriodBelowTheDecoderResolution_IsRefusedRatherThanExtended()
    {
        List<TimedScoreEvent> events =
            [Beat(0.0, 4, 4, 0, key: "C:major"), Beat(0.001, 4, 4, 2), Beat(0.002, 4, 4, 4)];
        Assert.Throws<BeatGridException>(() => AbcSerializer.EventsToAbc(events, 600.0));
    }

    [Fact]
    public void ANullArgument_IsRefused()
    {
        Assert.Throws<ArgumentNullException>(() => AbcSerializer.EventsToAbc(null!, 1.0));
        Assert.Throws<ArgumentNullException>(() => AbcSerializer.ScoreToAbc(null!));
        Assert.Throws<ArgumentNullException>(() => AbcPitchSpelling.ChordSymbolToAbc(null!));
        Assert.Throws<ArgumentNullException>(() => AbcPitchSpelling.KeySymbolToAbc(null!));
    }

    private static TimedScoreEvent Beat(double time, int numerator, int denominator, int eighth,
        string? key = null, string? chord = null, string? structure = null, TimedScoreNote[]? melody = null)
        => new()
        {
            Time = time,
            Rhythm = new ScoreRhythm((numerator, denominator), eighth),
            Key = key,
            Chord = chord,
            Structure = structure,
            Melody = melody,
        };

    /// <summary>Removes quoted chord symbols, leaving header and comment lines alone. The voice headers carry
    /// quotes of their own, so a blanket substitution would mangle them into <c>name=</c>.</summary>
    private static string StripChords(string text)
    {
        string[] lines = text.Split('\n');
        for (int i = 0; i < lines.Length; i++)
        {
            if (lines[i].StartsWith('%') || HeaderLine.IsMatch(lines[i])) continue;
            lines[i] = QuotedText.Replace(lines[i], "");
        }
        return string.Join("\n", lines);
    }

    private static List<TimedScoreEvent> ReadEvents(JsonElement events)
    {
        List<TimedScoreEvent> result = [];
        foreach (JsonElement item in events.EnumerateArray())
        {
            JsonElement meter = item.GetProperty("meter");
            JsonElement eighth = item.GetProperty("eighthPosition");
            ScoreRhythm? rhythm = null;
            if (meter.ValueKind != JsonValueKind.Null || eighth.ValueKind != JsonValueKind.Null)
            {
                rhythm = new ScoreRhythm(
                    meter.ValueKind == JsonValueKind.Null ? null : (meter[0].GetInt32(), meter[1].GetInt32()),
                    eighth.ValueKind == JsonValueKind.Null ? null : eighth.GetInt32());
            }
            List<TimedScoreNote> melody = [];
            foreach (JsonElement note in item.GetProperty("melody").EnumerateArray())
            {
                melody.Add(new TimedScoreNote(note.GetProperty("pitch").GetInt32(),
                    note.GetProperty("track").GetInt32(), note.GetProperty("endTime").GetDouble()));
            }
            result.Add(new TimedScoreEvent
            {
                Time = item.GetProperty("time").GetDouble(),
                Rhythm = rhythm,
                Key = Text(item, "key"),
                Structure = Text(item, "structure"),
                Chord = Text(item, "chord"),
                Melody = melody.Count > 0 ? melody : null,
            });
        }
        return result;
    }

    private static string? Text(JsonElement item, string name)
    {
        JsonElement value = item.GetProperty(name);
        return value.ValueKind == JsonValueKind.Null ? null : value.GetString();
    }

    private static void AssertNullableInt(JsonElement expected, int? actual)
    {
        if (expected.ValueKind == JsonValueKind.Null) Assert.Null(actual);
        else Assert.Equal(expected.GetInt32(), actual);
    }

    private static void AssertDoubles(JsonElement expected, double[] actual)
    {
        Assert.Equal(expected.GetArrayLength(), actual.Length);
        int index = 0;
        foreach (JsonElement value in expected.EnumerateArray())
        {
            Assert.Equal(value.GetDouble(), actual[index++], 12);
        }
    }

    /// <summary>Expands the fixture's run-length encoding of a per-subbeat array.</summary>
    private static int[] ExpandInts(JsonElement runs)
    {
        List<int> values = [];
        foreach (JsonElement run in runs.EnumerateArray())
        {
            values.AddRange(Enumerable.Repeat(run[1].GetInt32(), run[0].GetInt32()));
        }
        return [.. values];
    }

    private static string[] ExpandStrings(JsonElement runs)
    {
        List<string> values = [];
        foreach (JsonElement run in runs.EnumerateArray())
        {
            values.AddRange(Enumerable.Repeat(run[1].GetString()!, run[0].GetInt32()));
        }
        return [.. values];
    }
}
