using System.Text.Json;
using HartsyInference.Audio.Models.SheetSage2;
using Xunit;

namespace HartsyInference.Audio.Tests.Parity;

/// <summary>Gate S1: the C# vocabulary and decode grammar against the released implementation's own output.
///
/// <para>Checked against a committed dump rather than against a reading of the Python, because both are
/// checkpoint facts with no tolerance: the decoder's output projection is exactly as wide as the vocabulary, and
/// an id's meaning is decided purely by which range it lands in. The allow-mask is compared by exact cardinality
/// as well as by probe, so a range that is one token wide in the wrong direction cannot pass.</para>
///
/// <para>Needs no checkpoint, backend or GPU — the fixture is regenerated by
/// <c>tests/python-reference/dump_sheetsage2_reference.py</c>.</para></summary>
public sealed class SheetSage2GrammarParityTests
{
    private static readonly ScoreTokenizer Tok = new();
    private static readonly JsonElement Reference = LoadReference();

    private static JsonElement LoadReference()
    {
        string path = Path.Combine(AppContext.BaseDirectory, "python-reference", "sheetsage2_reference", "grammar.json");
        if (!File.Exists(path))
        {
            // Fall back to the source tree when the fixture was not copied next to the test binary.
            DirectoryInfo? dir = new(AppContext.BaseDirectory);
            while (dir is not null && !Directory.Exists(Path.Combine(dir.FullName, "tests", "python-reference")))
            {
                dir = dir.Parent;
            }
            path = Path.Combine(dir?.FullName ?? ".", "tests", "python-reference", "sheetsage2_reference", "grammar.json");
        }
        return JsonDocument.Parse(File.ReadAllText(path)).RootElement.Clone();
    }

    [Fact]
    public void Vocabulary_MatchesTheReference()
    {
        Assert.Equal(Reference.GetProperty("tokenCount").GetInt32(), Tok.TokenCount);
        Assert.Equal(Reference.GetProperty("chordLabels").GetInt32(), Tok.FullChordLabels.Count);
        Assert.Equal(Reference.GetProperty("meterPairs").GetInt32(), Tok.MeterPairs.Count);
        Assert.Equal(Reference.GetProperty("structureLabels").GetInt32(), ScoreTokenizer.StructureLabels.Length);
        Assert.Equal(Reference.GetProperty("durationTemplates").GetInt32(), ScoreTokenizer.DurationTemplates.Length);
    }

    [Fact]
    public void Ranges_MatchTheReference()
    {
        JsonElement ranges = Reference.GetProperty("ranges");
        Assert.Equal(ranges.GetArrayLength(), Tok.Ranges.Count);
        int i = 0;
        foreach (JsonElement range in ranges.EnumerateArray())
        {
            (string name, int start, int end) = Tok.Ranges[i++];
            Assert.Equal(range.GetProperty("name").GetString(), name);
            Assert.Equal(range.GetProperty("start").GetInt32(), start);
            Assert.Equal(range.GetProperty("end").GetInt32(), end);
        }
    }

    [Fact]
    public void PromptPrefix_MatchesTheReference()
    {
        int[] expected = [.. Reference.GetProperty("promptPrefix").EnumerateArray().Select(e => e.GetInt32())];
        Assert.Equal(expected, ScoreTokenizer.PromptPrefix());
    }

    [Fact]
    public void TokenTypes_MatchTheReference()
    {
        foreach (JsonProperty entry in Reference.GetProperty("tokenTypes").EnumerateObject())
        {
            Assert.Equal(entry.Value.GetString(), Tok.TokenType(int.Parse(entry.Name)));
        }
    }

    /// <summary>Every pinned grammar state, compared by exact allowed-token count and by one probe per field.</summary>
    [Fact]
    public void AllowMasks_MatchTheReference()
    {
        foreach (JsonProperty state in Reference.GetProperty("states").EnumerateObject())
        {
            bool[] allowed = Replay(state.Name);
            JsonElement want = state.Value;
            Assert.Equal(want.GetProperty("allowedCount").GetInt32(), allowed.Count(a => a));
            Assert.Equal(want.GetProperty("eos").GetBoolean(), allowed[ScoreTokenizer.EosToken]);
            foreach ((string field, int start) in Probes())
            {
                Assert.Equal(want.GetProperty(field).GetBoolean(), allowed[start]);
            }
        }
    }

    /// <summary>Gate S1b: a token stream read as events, field for field, against the released decode.</summary>
    [Fact]
    public void DecodedEvents_MatchTheReference()
    {
        JsonElement codec = Reference.GetProperty("codec");
        int[] stream = [.. codec.GetProperty("stream").EnumerateArray().Select(e => e.GetInt32())];
        List<ScoreEvent> events = new ScoreEventCodec(Tok).DecodeSequence(stream);

        JsonElement want = codec.GetProperty("events");
        Assert.Equal(want.GetArrayLength(), events.Count);
        int i = 0;
        foreach (JsonElement expected in want.EnumerateArray())
        {
            ScoreEvent got = events[i++];
            Assert.Equal(expected.GetProperty("subbeat").GetInt32(), got.Subbeat);
            AssertNullableDouble(expected.GetProperty("timestamp"), got.Timestamp);
            AssertNullableString(expected.GetProperty("structure"), got.Structure);
            AssertNullableString(expected.GetProperty("key"), got.Key);
            AssertNullableString(expected.GetProperty("chord"), got.Chord);

            JsonElement meter = expected.GetProperty("meter");
            if (meter.ValueKind == JsonValueKind.Null) Assert.Null(got.Rhythm?.Meter);
            else
            {
                Assert.Equal(meter[0].GetInt32(), got.Rhythm!.Value.Meter!.Value.Numerator);
                Assert.Equal(meter[1].GetInt32(), got.Rhythm!.Value.Meter!.Value.Denominator);
            }
            JsonElement eighth = expected.GetProperty("eighthPosition");
            if (eighth.ValueKind == JsonValueKind.Null) Assert.Null(got.Rhythm?.EighthPosition);
            else Assert.Equal(eighth.GetInt32(), got.Rhythm!.Value.EighthPosition);

            JsonElement melody = expected.GetProperty("melody");
            Assert.Equal(melody.GetArrayLength(), got.Melody?.Count ?? 0);
            int n = 0;
            foreach (JsonElement note in melody.EnumerateArray())
            {
                ScoreNote actual = got.Melody![n++];
                Assert.Equal(note.GetProperty("pitch").GetInt32(), actual.Pitch);
                Assert.Equal(note.GetProperty("track").GetInt32(), actual.Track);
                Assert.Equal(note.GetProperty("durationBin").GetInt32(), actual.DurationBin);
                Assert.Equal(note.GetProperty("durationSteps").GetInt32(), actual.DurationSteps);
            }
        }
    }

    /// <summary>Re-encoding has to spell gaps exactly as the reference spells them, because a later window
    /// replays its predecessor's events as context. It is canonical rather than byte-exact — see
    /// <see cref="ShiftRuns_CanonicaliseAsTheReferenceDoes"/> for the runs that do not survive a round trip.</summary>
    [Fact]
    public void ReEncodedEvents_MatchTheReference()
    {
        JsonElement codec = Reference.GetProperty("codec");
        int[] stream = [.. codec.GetProperty("stream").EnumerateArray().Select(e => e.GetInt32())];
        int[] expected = [.. codec.GetProperty("reencoded").EnumerateArray().Select(e => e.GetInt32())];
        ScoreEventCodec coder = new(Tok);
        Assert.Equal(expected, coder.EncodeEvents(coder.DecodeSequence(stream)));
        // The reference drops only the end token, so the round trip is the input minus its EOS.
        Assert.Equal(stream[..^1], expected);
    }

    [Fact]
    public void AStreamWithoutAPromptPrefix_IsRefused()
        => Assert.Throws<ArgumentException>(() => new ScoreEventCodec(Tok).DecodeSequence([Tok.TimeStart, ScoreTokenizer.EosToken]));

    [Fact]
    public void AnEventWithoutABeatPosition_IsRefused()
        => Assert.Throws<ArgumentException>(() => new ScoreEventCodec(Tok)
            .DecodeSequence([.. ScoreTokenizer.PromptPrefix(), Tok.TimeStart + 5, ScoreTokenizer.EosToken]));

    /// <summary>The shift runs a decode may legally write, and what re-encoding does with each.
    ///
    /// <para>Decoding keeps only the running total, so a run's shape is lost and the encoder re-spells every gap
    /// canonically. That is the reference's own behaviour, not a shortcut: <c>shift(100) shift(100)</c> comes
    /// back as one <c>shift(200)</c> there too. Pinned because the class documents exactly this limit, and
    /// because a port that silently canonicalised DIFFERENTLY would still pass every other gate here.</para></summary>
    [Fact]
    public void ShiftRuns_CanonicaliseAsTheReferenceDoes()
    {
        ScoreEventCodec coder = new(Tok);
        foreach (JsonProperty entry in Reference.GetProperty("shiftRuns").EnumerateObject())
        {
            JsonElement want = entry.Value;
            List<int> stream = [.. ScoreTokenizer.PromptPrefix()];
            foreach (JsonElement shift in want.GetProperty("shifts").EnumerateArray())
            {
                stream.Add(Tok.SubbeatShiftStart + shift.GetInt32());
            }
            stream.Add(Tok.TimeStart + 100);
            stream.Add(ScoreTokenizer.EosToken);

            List<ScoreEvent> events = coder.DecodeSequence(stream);
            Assert.Equal(want.GetProperty("subbeat").GetInt32(), Assert.Single(events).Subbeat);

            List<int> reencoded = coder.EncodeEvents(events);
            int[] shifts = [.. reencoded.Skip(ScoreTokenizer.PromptPrefix().Length).SkipLast(1)
                .Select(t => t - Tok.SubbeatShiftStart)];
            int[] expected = [.. want.GetProperty("reencodedShifts").EnumerateArray().Select(e => e.GetInt32())];
            Assert.Equal(expected, shifts);
            Assert.Equal(want.GetProperty("byteExact").GetBoolean(), reencoded.SequenceEqual(stream[..^1]));
        }
    }

    /// <summary>A gap past the grammar's own four-shift run limit. The encoder writes it anyway — confirmed
    /// against the reference — because a replayed prefix is context, not something the grammar is masking.</summary>
    [Fact]
    public void AGapPastTheGrammarLimit_IsWrittenNotCapped()
    {
        JsonElement want = Reference.GetProperty("shiftRuns").GetProperty("pastGrammarLimit");
        Assert.Equal(5, want.GetProperty("reencodedShifts").GetArrayLength());
        List<int> tokens = new ScoreEventCodec(Tok).EncodeEvents(
            [new ScoreEvent { Subbeat = want.GetProperty("subbeat").GetInt32(), TokensByField = [] }]);
        int[] shifts = [.. tokens.Skip(ScoreTokenizer.PromptPrefix().Length).Select(t => t - Tok.SubbeatShiftStart)];
        Assert.Equal([.. want.GetProperty("reencodedShifts").EnumerateArray().Select(e => e.GetInt32())], shifts);
    }

    /// <summary>A window cut at its generation stop ends mid-run. Those trailing shifts are dropped, as in the
    /// reference — they sit past everything the window is trusted for, and the next window's prefix is selected
    /// by timestamp, which a bare shift does not carry.</summary>
    [Fact]
    public void ATruncatedTail_DropsTheTrailingShiftRun()
    {
        JsonElement want = Reference.GetProperty("truncatedTail");
        int[] stream = [.. want.GetProperty("stream").EnumerateArray().Select(e => e.GetInt32())];
        Assert.Equal(want.GetProperty("eventCount").GetInt32(), new ScoreEventCodec(Tok).DecodeSequence(stream).Count);
    }

    /// <summary>Re-basing is the one operation that can drive a position backwards, and the reference turns a
    /// negative one into a token id outside the shift range without a word. This refuses instead.</summary>
    [Fact]
    public void EventsThatMoveBackwards_AreRefused()
    {
        ScoreEventCodec coder = new(Tok);
        Assert.Throws<ArgumentException>(() => coder.EncodeEvents(
            [new ScoreEvent { Subbeat = -300, TokensByField = [] }]));
        Assert.Throws<ArgumentException>(() => coder.EncodeEvents([
            new ScoreEvent { Subbeat = 10, TokensByField = [] },
            new ScoreEvent { Subbeat = 4, TokensByField = [] },
        ]));
    }

    /// <summary>A melody bucket opening with a note length. The reference reads it as pitch 256 — a phantom low
    /// note on the instrumental line — where silent musical garbage is the worst possible outcome.</summary>
    [Fact]
    public void AMelodyWithoutAPitch_IsRefused()
    {
        Assert.Throws<ArgumentException>(() => new ScoreEventCodec(Tok).DecodeSequence(
            [.. ScoreTokenizer.PromptPrefix(), Tok.SubbeatShiftStart + 1, Tok.DurationStart + 3, ScoreTokenizer.EosToken]));
    }

    [Fact]
    public void ANullTokenizer_IsRefusedAtConstruction()
    {
        Assert.Throws<ArgumentNullException>(() => new ScoreEventCodec(null!));
        Assert.Throws<ArgumentNullException>(() => new PromptGrammar(null!));
    }

    /// <summary>A note's length is derived from its bin, so the two cannot disagree on a hand-built note.</summary>
    [Fact]
    public void ANotesLength_FollowsItsBin()
    {
        for (int bin = 0; bin < ScoreTokenizer.DurationTemplates.Length; bin++)
        {
            Assert.Equal(ScoreTokenizer.DurationTemplates[bin], new ScoreNote(60, 0, bin).DurationSteps);
        }
    }

    /// <summary>Every pinned clip length, window for window. A plan that drifts by a second reads the wrong
    /// audio into every later window, which shows up as a plausible transcription of the wrong part of a song.</summary>
    [Fact]
    public void WindowPlans_MatchTheReference()
    {
        foreach (JsonProperty entry in Reference.GetProperty("windows").EnumerateObject())
        {
            double duration = double.Parse(entry.Name);
            IReadOnlyList<SheetSage2Window> actual = SlidingWindowPlan.For(duration);
            Assert.Equal(entry.Value.GetArrayLength(), actual.Count);
            int i = 0;
            foreach (JsonElement want in entry.Value.EnumerateArray())
            {
                SheetSage2Window got = actual[i];
                Assert.Equal(want.GetProperty("start").GetDouble(), got.Start, 6);
                Assert.Equal(want.GetProperty("end").GetDouble(), got.End, 6);
                Assert.Equal(want.GetProperty("acceptStart").GetDouble(), got.AcceptStart, 6);
                Assert.Equal(want.GetProperty("acceptEnd").GetDouble(), got.AcceptEnd, 6);
                Assert.Equal(want.GetProperty("prefixEnd").GetDouble(), got.PrefixEnd, 6);
                JsonElement stop = want.GetProperty("generationStop");
                if (stop.ValueKind == JsonValueKind.Null) Assert.Null(got.GenerationStop);
                else Assert.Equal(stop.GetDouble(), got.GenerationStop!.Value, 6);
                i++;
            }
        }
    }

    /// <summary>Whatever the plan's shape, the accepted spans have to tile the clip exactly once — a gap drops
    /// a passage from the transcription and an overlap transcribes it twice.</summary>
    [Theory]
    [InlineData(30.0)]
    [InlineData(300.0)]
    [InlineData(301.0)]
    [InlineData(450.0)]
    [InlineData(905.0)]
    [InlineData(3600.0)]
    public void AcceptedSpans_TileTheClipExactlyOnce(double duration)
    {
        IReadOnlyList<SheetSage2Window> windows = SlidingWindowPlan.For(duration);
        Assert.Equal(0.0, windows[0].AcceptStart, 6);
        Assert.Equal(duration, windows[^1].AcceptEnd, 6);
        for (int i = 0; i < windows.Count; i++)
        {
            Assert.True(windows[i].AcceptEnd > windows[i].AcceptStart, $"window {i} accepts nothing");
            // Everything a window is trusted for has to be inside the audio it actually read.
            Assert.True(windows[i].AcceptStart >= windows[i].Start - 1e-6, $"window {i} accepts before it starts");
            Assert.True(windows[i].AcceptEnd <= windows[i].End + 1e-6, $"window {i} accepts past its own audio");
            if (i > 0) Assert.Equal(windows[i - 1].AcceptEnd, windows[i].AcceptStart, 6);
        }
    }

    [Fact]
    public void ShortClips_AreOneWindowWithNoLookahead()
    {
        IReadOnlyList<SheetSage2Window> windows = SlidingWindowPlan.For(120.0);
        SheetSage2Window only = Assert.Single(windows);
        Assert.Null(only.GenerationStop);
        Assert.Equal(0.0, only.Start, 6);
        Assert.Equal(120.0, only.End, 6);
    }

    [Fact]
    public void ADurationThatIsNotPositive_IsRefused()
    {
        Assert.Throws<ArgumentOutOfRangeException>(() => SlidingWindowPlan.For(0));
        Assert.Throws<ArgumentOutOfRangeException>(() => SlidingWindowPlan.For(double.NaN));
    }

    private static void AssertNullableDouble(JsonElement expected, double? actual)
    {
        if (expected.ValueKind == JsonValueKind.Null) Assert.Null(actual);
        else Assert.Equal(expected.GetDouble(), actual!.Value, 6);
    }

    private static void AssertNullableString(JsonElement expected, string? actual)
    {
        if (expected.ValueKind == JsonValueKind.Null) Assert.Null(actual);
        else Assert.Equal(expected.GetString(), actual);
    }

    private (string Field, int Start)[] Probes() =>
    [
        ("subbeat_shift", Tok.SubbeatShiftStart), ("time", Tok.TimeStart), ("meter", Tok.MeterStart),
        ("eighth_position", Tok.EighthPositionStart), ("structure", Tok.StructureStart), ("key", Tok.KeyStart),
        ("majmin_chord", Tok.MajMinChordStart), ("full_chord", Tok.FullChordStart), ("pitch", Tok.PitchStart),
        ("duration", Tok.DurationStart),
    ];

    /// <summary>The same update sequences the dump script drives its states with.</summary>
    private bool[] Replay(string state)
    {
        PromptGrammar grammar = new(Tok);
        foreach ((string field, int offset) in Updates(state))
        {
            grammar.Update(Start(field) + offset);
        }
        return grammar.Allowed();
    }

    private static (string Field, int Offset)[] Updates(string state) => state switch
    {
        "fresh" => [],
        "after_time" => [("time", 10)],
        "after_meter" => [("meter", 3)],
        "after_pitch" => [("pitch", 60)],
        "after_key" => [("key", 1)],
        "after_pitch_duration" => [("key", 1), ("pitch", 60), ("duration", 2)],
        "shift1" => [("subbeat_shift", 0)],
        "shift4" => [.. Enumerable.Repeat(("subbeat_shift", 0), 4)],
        "shift5" => [.. Enumerable.Repeat(("subbeat_shift", 0), 5)],
        "event_then_shift" => [("key", 1), ("subbeat_shift", 1)],
        _ => throw new InvalidOperationException($"The fixture pins a grammar state '{state}' this test cannot replay."),
    };

    private int Start(string field) => field switch
    {
        "subbeat_shift" => Tok.SubbeatShiftStart,
        "time" => Tok.TimeStart,
        "meter" => Tok.MeterStart,
        "eighth_position" => Tok.EighthPositionStart,
        "structure" => Tok.StructureStart,
        "key" => Tok.KeyStart,
        "majmin_chord" => Tok.MajMinChordStart,
        "full_chord" => Tok.FullChordStart,
        "pitch" => Tok.PitchStart,
        "duration" => Tok.DurationStart,
        _ => throw new InvalidOperationException($"Unknown field '{field}'."),
    };
}
