using HartsyInference.Audio.Preprocessing;
using Xunit;

namespace HartsyInference.Audio.Tests;

/// <summary>Numeric parity for <see cref="KaldiFbankExtractor"/> against <c>torchaudio.compliance.kaldi.fbank</c>
/// (the feature CAM++ / CosyVoice consume). The reference is generated by <c>tests/.../kaldi_ref.py</c>:
/// it writes the input samples to <c>kaldi_in.f32</c> and the <c>[T,80]</c> fbank to <c>kaldi_ref.f32</c>.
/// Point <c>HARTSYINFERENCE_KALDI_REF_DIR</c> at that directory to run; the test self-skips otherwise so CI
/// stays self-contained.</summary>
public sealed class KaldiFbankParityTests
{
    private static string? RefDir => Environment.GetEnvironmentVariable("HARTSYINFERENCE_KALDI_REF_DIR");

    [Fact]
    public void Fbank_MatchesTorchaudioKaldi()
    {
        string? dir = RefDir;
        if (dir is null) { Assert.True(true, "set HARTSYINFERENCE_KALDI_REF_DIR to run"); return; }
        string inPath = Path.Combine(dir, "kaldi_in.f32");
        string refPath = Path.Combine(dir, "kaldi_ref.f32");
        Assert.True(File.Exists(inPath) && File.Exists(refPath), $"missing reference files in {dir}");

        float[] audio = ReadF32(inPath);
        float[] reference = ReadF32(refPath);

        const int bins = 80;
        KaldiFbankExtractor ext = new(16_000, bins);
        float[,] feat = ext.Compute(audio);
        int frames = feat.GetLength(0);
        Assert.Equal(reference.Length, frames * bins);

        float maxAbs = 0f, sumAbs = 0f;
        for (int t = 0; t < frames; t++)
            for (int m = 0; m < bins; m++)
            {
                float diff = MathF.Abs(feat[t, m] - reference[t * bins + m]);
                maxAbs = MathF.Max(maxAbs, diff);
                sumAbs += diff;
            }
        float meanAbs = sumAbs / (frames * bins);
        // Float STFT/mel accumulation order differs from torch; allow a small absolute tolerance on log-fbank.
        Assert.True(maxAbs < 2e-2f, $"max abs diff {maxAbs} (mean {meanAbs}) exceeds 2e-2 vs torchaudio kaldi fbank");
    }

    private static float[] ReadF32(string path)
    {
        byte[] bytes = File.ReadAllBytes(path);
        float[] f = new float[bytes.Length / 4];
        Buffer.BlockCopy(bytes, 0, f, 0, f.Length * 4);
        return f;
    }
}
