using Xunit;
using Xunit.Abstractions;
using HartsyInference.Audio.Cache;
using HartsyInference.Audio.Models.Moonshine;
using HartsyInference.Core.Tensors;
using HartsyInference.Cpu;
using HartsyInference.ModelHandler.SafeTensors;
using HartsyInference.Tests.Common;

namespace HartsyInference.Audio.Tests;

/// <summary>Real-weight parity for the 2nd-gen streaming Moonshine port vs the real HuggingFace
/// <c>transformers</c> (&gt;=5.14) <c>MoonshineStreamingForConditionalGeneration</c> reference, on the real
/// <c>UsefulSensors/moonshine-streaming-tiny</c> checkpoint (auto-downloaded via <see cref="AudioModelCache"/>
/// — same cache the pipeline itself uses). Fixtures generated by
/// <c>tests/python-reference/moonshine_streaming_parity/gen_reference.py</c> (gitignored <c>*.bin</c>);
/// skip-guarded when either is unavailable.</summary>
[Trait("Category", "Integration")]
public class MoonshineStreamingParityTests
{
    private readonly ITestOutputHelper _output;
    public MoonshineStreamingParityTests(ITestOutputHelper output) => _output = output;

    [Fact]
    public async Task Forward_MatchesTransformersReference_OnRealWeights()
    {
        string fixtureDir = System.IO.Path.Combine(RepoRoot.Path, "tests", "python-reference", "moonshine_streaming_parity");
        string metaPath = System.IO.Path.Combine(fixtureDir, "meta.txt");
        if (!File.Exists(metaPath))
        {
            _output.WriteLine("Reference fixtures not present — skipping.");
            return;
        }

        Dictionary<string, int> meta = File.ReadAllLines(metaPath)
            .Select(l => l.Split('='))
            .ToDictionary(p => p[0], p => int.Parse(p[1]));
        int t0 = meta["T0"], encoderT = meta["encoder_T"], vocab = meta["vocab"], promptLen = meta["prompt_len"];

        string repoDir;
        try
        {
            repoDir = AudioModelCache.GetRepoDirectory("UsefulSensors/moonshine-streaming-tiny");
            await AudioModelCache.GetAsync("UsefulSensors/moonshine-streaming-tiny", "model.safetensors");
            await AudioModelCache.GetAsync("UsefulSensors/moonshine-streaming-tiny", "tokenizer.json");
        }
        catch (Exception ex)
        {
            _output.WriteLine($"Checkpoint unavailable — skipping. ({ex.Message})");
            return;
        }

        MoonshineConfig cfg = MoonshineConfig.StreamingTiny;
        using SafeTensorsLoader loader = new();
        loader.Load(System.IO.Path.Combine(repoDir, "model.safetensors"));
        Dictionary<string, Tensor> weights = loader.GetAllTensors();

        using MoonshineStreamingEncoder encoder = new(cfg);
        encoder.LoadWeights(weights);
        using MoonshineStreamingDecoder decoder = new(cfg);
        decoder.LoadWeights(weights);
        using CpuBackend backend = new();

        float[] audio = ReadFloatBin(System.IO.Path.Combine(fixtureDir, "audio.bin"), t0 * 80);
        Tensor encoded = encoder.Forward(backend, audio);
        Assert.Equal(new TensorShape(1, encoderT, cfg.EncoderHiddenSize), encoded.Shape);

        Tensor encRef = ReadTensorBin(System.IO.Path.Combine(fixtureDir, "encoder_hidden_ref.bin"), new TensorShape(1, encoderT, cfg.EncoderHiddenSize));
        (float encCosine, float encMaxAbs) = Compare(encoded, encRef);
        _output.WriteLine($"encoder cosine={encCosine:F6} maxAbsDiff={encMaxAbs:E4}");
        Assert.True(encCosine > 0.999f, $"encoder cosine {encCosine} too low.");

        int[] promptTokens = ReadIntBin(System.IO.Path.Combine(fixtureDir, "prompt_tokens.bin"), promptLen);
        using MoonshineDecoder.DecodeState state = decoder.StartDecode(backend, encoded);
        Tensor logits = decoder.DecodeStep(backend, promptTokens, state);
        encoded.Dispose();
        encRef.Dispose();

        Tensor logitsRef = ReadTensorBin(System.IO.Path.Combine(fixtureDir, "logits_last_ref.bin"), new TensorShape(1, vocab));
        (float logitsCosine, float logitsMaxAbs) = Compare(logits, logitsRef);
        logits.Dispose();
        logitsRef.Dispose();

        _output.WriteLine($"decoder logits cosine={logitsCosine:F6} maxAbsDiff={logitsMaxAbs:E4}");
        Assert.True(logitsCosine > 0.999f, $"decoder logits cosine {logitsCosine} too low.");
    }

    private static unsafe Tensor ReadTensorBin(string path, TensorShape shape)
    {
        byte[] bytes = File.ReadAllBytes(path);
        Tensor t = new(shape, DType.F32);
        fixed (byte* src = bytes) Buffer.MemoryCopy(src, (void*)t.DataPointer, bytes.Length, bytes.Length);
        return t;
    }

    private static float[] ReadFloatBin(string path, int count)
    {
        byte[] bytes = File.ReadAllBytes(path);
        float[] result = new float[count];
        Buffer.BlockCopy(bytes, 0, result, 0, count * 4);
        return result;
    }

    private static int[] ReadIntBin(string path, int count)
    {
        byte[] bytes = File.ReadAllBytes(path);
        int[] result = new int[count];
        Buffer.BlockCopy(bytes, 0, result, 0, count * 4);
        return result;
    }

    private static unsafe (float Cosine, float MaxAbsDiff) Compare(Tensor a, Tensor b)
    {
        long n = a.Shape.ElementCount;
        float* pa = (float*)a.DataPointer;
        float* pb = (float*)b.DataPointer;
        double dot = 0, na = 0, nb = 0;
        float maxAbsDiff = 0;
        for (long i = 0; i < n; i++)
        {
            dot += (double)pa[i] * pb[i];
            na += (double)pa[i] * pa[i];
            nb += (double)pb[i] * pb[i];
            maxAbsDiff = MathF.Max(maxAbsDiff, MathF.Abs(pa[i] - pb[i]));
        }
        float cosine = (float)(dot / (Math.Sqrt(na) * Math.Sqrt(nb) + 1e-12));
        return (cosine, maxAbsDiff);
    }
}
