using HartsyInference.Audio.Dsp;
using HartsyInference.Core.Tensors;
using Xunit;

namespace HartsyInference.Audio.Tests;

/// <summary>The NSF harmonic source is generated by several workers that jump the phase accumulators and the
/// noise generator to their start; every model that streams it (CosyVoice) or reproduces a fixed-seed
/// waveform (Kokoro, RVC) depends on the split being invisible. These pin the RNG jump to the sequential
/// walk and the multi-worker source to the single-worker one, sample for sample.</summary>
public sealed unsafe class NsfVocoderDspTests
{
    [Theory]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(7)]
    [InlineData(1000)]
    [InlineData(123_457)]
    public void Advance_MatchesSequentialWalk(int steps)
    {
        uint walked = 0x9E3779B9u;
        for (int i = 0; i < steps; i++) DeterministicRng.NextUniform(ref walked);
        Assert.Equal(walked, DeterministicRng.Advance(0x9E3779B9u, steps));
        Assert.Equal(0x9E3779B9u, DeterministicRng.Advance(0x9E3779B9u, 0));
    }

    [Theory]
    [InlineData(true)]
    [InlineData(false)]
    public void HarmonicSource_ParallelWorkersMatchSequential(bool addNoise)
    {
        const int frames = 700, scale = 12, harmonics = 5, sampleRate = 24_000;
        Random rng = new(7);
        float[] f0 = new float[frames];
        for (int i = 0; i < frames; i++)
        {
            // Voiced runs with unvoiced gaps, so both branches of the amplitude shaping run.
            f0[i] = (i / 50) % 3 == 2 ? 0f : 90f + 200f * (float)rng.NextDouble();
        }
        using Tensor mergeW = new(new TensorShape(1, harmonics), DType.F32);
        using Tensor mergeB = new(new TensorShape(1), DType.F32);
        Span<float> w = mergeW.AsSpan<float>();
        for (int h = 0; h < harmonics; h++) w[h] = 0.3f - 0.05f * h;
        mergeB.AsSpan<float>()[0] = 0.01f;

        double[] phaseSeq = new double[harmonics];
        uint rngSeq = 0x9E3779B9u;
        float[] sequential = NsfVocoderDsp.GenerateHarmonicSourceChunk(f0, phaseSeq, ref rngSeq, scale, sampleRate, harmonics,
            mergeW, mergeB, 0.1f, 0.003f, 10f, addNoise, maxWorkers: 1);

        double[] phasePar = new double[harmonics];
        uint rngPar = 0x9E3779B9u;
        float[] parallel = NsfVocoderDsp.GenerateHarmonicSourceChunk(f0, phasePar, ref rngPar, scale, sampleRate, harmonics,
            mergeW, mergeB, 0.1f, 0.003f, 10f, addNoise, maxWorkers: 6);

        Assert.Equal(sequential.Length, parallel.Length);
        Assert.Equal(rngSeq, rngPar);
        int exact = 0;
        for (int i = 0; i < sequential.Length; i++)
        {
            // The only difference is the per-worker starting phase, recovered from one cumulative F0 sum instead
            // of the step-by-step mod-1 walk: a double-rounding-level deviation, far inside float resolution.
            Assert.True(MathF.Abs(sequential[i] - parallel[i]) <= 1e-6f, $"sample {i}: {sequential[i]} vs {parallel[i]}");
            if (sequential[i] == parallel[i]) exact++;
        }
        Assert.True(exact > sequential.Length * 0.99, $"only {exact}/{sequential.Length} samples bit-identical");
        for (int h = 0; h < harmonics; h++)
        {
            Assert.True(Math.Abs(phaseSeq[h] - phasePar[h]) < 1e-9, $"harmonic {h}: final phase {phaseSeq[h]} vs {phasePar[h]}");
        }
    }
}
