using Xunit;
using Xunit.Abstractions;
using HartsyInference.Audio.Models.ZipVoice;
using HartsyInference.Core.Tensors;
using HartsyInference.Cpu;
using HartsyInference.ModelHandler.SafeTensors;
using HartsyInference.Tests.Common;

namespace HartsyInference.Audio.Tests;

/// <summary>Real-weight parity for the from-scratch ZipVoice (k2-fsa/ZipVoice) Zipformer-backbone port vs the
/// real <c>k2-fsa/ZipVoice</c> Python source (<c>zipvoice.models.modules.zipformer.TTSZipformer</c>), on the
/// real <c>k2-fsa/ZipVoice</c> checkpoint. Covers both backbones (<c>fm_decoder</c>, time-conditioned, 5
/// U-Net-shaped stages; <c>text_encoder</c>, unconditional, single stage) plus the pure-integer "average
/// upsampling" frame-to-token-index logic in <see cref="ZipVoiceModel.BuildFrameToTokenIndex"/>. Fixtures
/// generated by <c>tests/python-reference/zipvoice_parity/gen_reference.py</c> (gitignored <c>*.bin</c>);
/// skip-guarded when either the fixtures or the checkpoint are unavailable. The tokenizer (English espeak-IPA
/// g2p) is intentionally out of scope here — see <see cref="ZipVoiceTokenizer"/>'s doc comment.</summary>
[Trait("Category", "Integration")]
public class ZipVoiceParityTests
{
    private readonly ITestOutputHelper _output;
    public ZipVoiceParityTests(ITestOutputHelper output) => _output = output;

    private const string CheckpointPath =
        "/home/hartsy/.cache/huggingface/hub/models--k2-fsa--ZipVoice/snapshots/" +
        "4ed45fb6e7e9527b780bef9e097a04bf13fe4e6b/zipvoice/model.safetensors";

    [Fact]
    public void FrameToTokenIndex_MatchesPythonReference()
    {
        string fixtureDir = System.IO.Path.Combine(RepoRoot.Path, "tests", "python-reference", "zipvoice_parity");
        string idxPath = System.IO.Path.Combine(fixtureDir, "frame_to_token_index_ref.bin");
        if (!File.Exists(idxPath))
        {
            _output.WriteLine("Reference fixtures not present — skipping.");
            return;
        }

        // Mirrors gen_reference.py's duration-index check: tokens_len=9, features_len=41.
        int[] expected = ReadIntBin(idxPath, 41);
        int[] actual = ZipVoiceModel.BuildFrameToTokenIndex(9, 41);

        Assert.Equal(expected.Length, actual.Length);
        Assert.Equal(expected, actual);
        _output.WriteLine("frame-to-token index matches Python reference exactly (41 frames, 9 tokens).");
    }

    [Fact]
    public void FmDecoder_MatchesPythonReference_OnRealWeights()
    {
        string fixtureDir = System.IO.Path.Combine(RepoRoot.Path, "tests", "python-reference", "zipvoice_parity");
        string metaPath = System.IO.Path.Combine(fixtureDir, "meta.txt");
        if (!File.Exists(metaPath) || !File.Exists(CheckpointPath))
        {
            _output.WriteLine("Reference fixtures or checkpoint not present — skipping.");
            return;
        }

        Dictionary<string, string> meta = ReadMeta(metaPath);
        int t = int.Parse(meta["fm_T"]);
        int inDim = int.Parse(meta["fm_in_dim"]);
        int outDim = int.Parse(meta["fm_out_dim"]);
        float timestep = float.Parse(meta["fm_t"]);

        using SafeTensorsLoader loader = new();
        loader.Load(CheckpointPath);
        Dictionary<string, Tensor> weights = loader.GetAllTensors();

        ZipVoiceConfig cfg = ZipVoiceConfig.Default;
        TTSZipformer fmDecoder = new(
            inDim: cfg.FeatDim * 3, dim: cfg.FmDecoderDim, outDim: cfg.FeatDim,
            timeEmbedDim: cfg.TimeEmbedDim, useTimeEmb: true,
            downsamplingFactor: cfg.FmDecoderDownsamplingFactor, numLayers: cfg.FmDecoderNumLayers,
            cnnKernel: cfg.FmDecoderCnnModuleKernel, numHeads: cfg.FmDecoderNumHeads, queryHeadDim: cfg.QueryHeadDim,
            posHeadDim: cfg.PosHeadDim, posDim: cfg.PosDim, valueHeadDim: cfg.ValueHeadDim,
            feedforwardDim: cfg.FmDecoderFeedforwardDim);
        fmDecoder.LoadWeights(weights, "fm_decoder");

        using CpuBackend backend = new();
        Tensor x = ReadTensorBin(System.IO.Path.Combine(fixtureDir, "fm_x.bin"), new TensorShape(1, t, inDim));
        Tensor output = fmDecoder.Forward(backend, x, t, timestep);
        x.Dispose();

        Assert.Equal(new TensorShape(1, t, outDim), output.Shape);

        Tensor reference = ReadTensorBin(System.IO.Path.Combine(fixtureDir, "fm_out_ref.bin"), new TensorShape(1, t, outDim));
        (float cosine, float maxAbsDiff) = Compare(output, reference);
        output.Dispose();
        reference.Dispose();

        _output.WriteLine($"fm_decoder cosine={cosine:F6} maxAbsDiff={maxAbsDiff:E4}");
        Assert.True(cosine > 0.999f, $"fm_decoder cosine {cosine} too low.");
    }

    [Fact]
    public void TextEncoder_MatchesPythonReference_OnRealWeights()
    {
        string fixtureDir = System.IO.Path.Combine(RepoRoot.Path, "tests", "python-reference", "zipvoice_parity");
        string metaPath = System.IO.Path.Combine(fixtureDir, "meta.txt");
        if (!File.Exists(metaPath) || !File.Exists(CheckpointPath))
        {
            _output.WriteLine("Reference fixtures or checkpoint not present — skipping.");
            return;
        }

        Dictionary<string, string> meta = ReadMeta(metaPath);
        int t = int.Parse(meta["te_T"]);
        int inDim = int.Parse(meta["te_in_dim"]);
        int outDim = int.Parse(meta["te_out_dim"]);

        using SafeTensorsLoader loader = new();
        loader.Load(CheckpointPath);
        Dictionary<string, Tensor> weights = loader.GetAllTensors();

        ZipVoiceConfig cfg = ZipVoiceConfig.Default;
        TTSZipformer textEncoder = new(
            inDim: cfg.TextEmbedDim, dim: cfg.TextEncoderDim, outDim: cfg.FeatDim,
            timeEmbedDim: cfg.TimeEmbedDim, useTimeEmb: false,
            downsamplingFactor: [1], numLayers: [cfg.TextEncoderNumLayers], cnnKernel: [cfg.TextEncoderCnnModuleKernel],
            numHeads: cfg.TextEncoderNumHeads, queryHeadDim: cfg.QueryHeadDim, posHeadDim: cfg.PosHeadDim,
            posDim: cfg.PosDim, valueHeadDim: cfg.ValueHeadDim, feedforwardDim: cfg.TextEncoderFeedforwardDim);
        textEncoder.LoadWeights(weights, "text_encoder");

        using CpuBackend backend = new();
        Tensor x = ReadTensorBin(System.IO.Path.Combine(fixtureDir, "te_x.bin"), new TensorShape(1, t, inDim));
        Tensor output = textEncoder.Forward(backend, x, t, timestep: null);
        x.Dispose();

        Assert.Equal(new TensorShape(1, t, outDim), output.Shape);

        Tensor reference = ReadTensorBin(System.IO.Path.Combine(fixtureDir, "te_out_ref.bin"), new TensorShape(1, t, outDim));
        (float cosine, float maxAbsDiff) = Compare(output, reference);
        output.Dispose();
        reference.Dispose();

        _output.WriteLine($"text_encoder cosine={cosine:F6} maxAbsDiff={maxAbsDiff:E4}");
        Assert.True(cosine > 0.999f, $"text_encoder cosine {cosine} too low.");
    }

    private static Dictionary<string, string> ReadMeta(string path) => File.ReadAllLines(path)
        .Where(l => l.Contains('='))
        .Select(l => l.Split('=', 2))
        .ToDictionary(p => p[0], p => p[1]);

    private static unsafe Tensor ReadTensorBin(string path, TensorShape shape)
    {
        byte[] bytes = File.ReadAllBytes(path);
        Tensor t = new(shape, DType.F32);
        fixed (byte* src = bytes) Buffer.MemoryCopy(src, (void*)t.DataPointer, bytes.Length, bytes.Length);
        return t;
    }

    private static int[] ReadIntBin(string path, int count)
    {
        byte[] bytes = File.ReadAllBytes(path);
        int[] result = new int[count];
        Buffer.BlockCopy(bytes, 0, result, 0, count * 4);
        return result;
    }

    private static unsafe (float Cosine, float MaxAbsDiff) Compare(Tensor a, Tensor b)
    {
        long n = a.Shape.ElementCount;
        float* pa = (float*)a.DataPointer;
        float* pb = (float*)b.DataPointer;
        double dot = 0, na = 0, nb = 0;
        float maxAbsDiff = 0;
        for (long i = 0; i < n; i++)
        {
            dot += (double)pa[i] * pb[i];
            na += (double)pa[i] * pa[i];
            nb += (double)pb[i] * pb[i];
            maxAbsDiff = MathF.Max(maxAbsDiff, MathF.Abs(pa[i] - pb[i]));
        }
        float cosine = (float)(dot / (Math.Sqrt(na) * Math.Sqrt(nb) + 1e-12));
        return (cosine, maxAbsDiff);
    }
}
