"""
Generates SDXL reference images for the SSIM gate. Produces deterministic outputs at
small resolution (small enough that 20-step generation completes in seconds even on CPU)
that the C# `SdxlSsimTests` compare against.

Output: tests/python-reference/sdxl_reference_images/
  prompts.json             # prompt list + seed + steps + cfg + resolution
  init_noise_seed42.bin    # F32 [1, 4, latentH, latentW] — initial noise tensor for seed 42
  ref_<idx>.png            # PNG image generated by diffusers
  meta.json                # prompt → ref_<idx>.png mapping + checkpoint hash

Usage:
    python dump_sdxl_reference_image.py --checkpoint /path/to/JuggernautXL.safetensors \\
        --output ./sdxl_reference_images --width 256 --height 256 --steps 20

The C# tests in tests/SharpInference.Diffusion.Tests/SdxlSsimTests.cs load the
generated PNGs as reference and compare against fresh generations. The strict
SSIM > 0.95 gate requires noise-injection into the C# pipeline; until that's
wired the tests run with a relaxed threshold (see test file for current value).
"""
import argparse
import hashlib
import json
import os
from pathlib import Path

import torch
import numpy as np
from diffusers import StableDiffusionXLPipeline, EulerDiscreteScheduler
from PIL import Image


PROMPTS = [
    "A photograph of an astronaut riding a horse on the moon",
    "A still life of a bowl of fruit on a wooden table, oil painting",
    "A red sports car parked in front of a modern house, sunset lighting",
    "A bookshelf with old leather-bound books and a brass reading lamp",
    "A mountain landscape with snow-capped peaks reflected in a still lake",
]

NEGATIVE = "blurry, low quality, distorted, watermark, signature"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint", required=True,
                        help="Path to SDXL single-file safetensors (e.g. JuggernautXL).")
    parser.add_argument("--output", required=True,
                        help="Output directory for reference images and metadata.")
    parser.add_argument("--width", type=int, default=256)
    parser.add_argument("--height", type=int, default=256)
    parser.add_argument("--steps", type=int, default=20)
    parser.add_argument("--cfg", type=float, default=7.5)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    out = Path(args.output)
    out.mkdir(parents=True, exist_ok=True)

    pipe = StableDiffusionXLPipeline.from_single_file(
        args.checkpoint,
        torch_dtype=torch.float16,
        use_safetensors=True,
    ).to("cuda" if torch.cuda.is_available() else "cpu")
    pipe.scheduler = EulerDiscreteScheduler.from_config(pipe.scheduler.config)

    latent_h = args.height // 8
    latent_w = args.width // 8

    generator = torch.Generator(device="cpu").manual_seed(args.seed)
    init_noise = torch.randn(1, 4, latent_h, latent_w, generator=generator, dtype=torch.float32)
    init_noise.numpy().astype(np.float32).tofile(out / f"init_noise_seed{args.seed}.bin")

    meta = {
        "checkpoint": str(args.checkpoint),
        "checkpoint_md5": _md5(args.checkpoint),
        "width": args.width,
        "height": args.height,
        "steps": args.steps,
        "cfg": args.cfg,
        "seed": args.seed,
        "scheduler": "EulerDiscreteScheduler",
        "negative_prompt": NEGATIVE,
        "prompts": [],
    }

    for idx, prompt in enumerate(PROMPTS):
        gen = torch.Generator(device="cpu").manual_seed(args.seed)
        result = pipe(
            prompt=prompt,
            negative_prompt=NEGATIVE,
            width=args.width,
            height=args.height,
            num_inference_steps=args.steps,
            guidance_scale=args.cfg,
            generator=gen,
        ).images[0]

        png_name = f"ref_{idx:02d}.png"
        rgb_name = f"ref_{idx:02d}.rgb"
        result.save(out / png_name)

        # Also dump raw RGB bytes (interleaved [H, W, 3], uint8) for C# to load
        # without needing a PNG decoder dependency.
        rgb_array = np.array(result.convert("RGB"), dtype=np.uint8)
        assert rgb_array.shape == (args.height, args.width, 3), f"unexpected shape {rgb_array.shape}"
        rgb_array.tofile(out / rgb_name)

        meta["prompts"].append({
            "index": idx,
            "prompt": prompt,
            "image": png_name,
            "rgb": rgb_name,
        })
        print(f"[{idx + 1}/{len(PROMPTS)}] {prompt[:60]}... → {png_name} (+{rgb_name})")

    with open(out / "meta.json", "w") as f:
        json.dump(meta, f, indent=2)

    print(f"\nReference images written to {out}")


def _md5(path):
    h = hashlib.md5()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


if __name__ == "__main__":
    main()
