<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>HartsyInference.ThreeD.Cli</RootNamespace>
    <AssemblyName>hartsyinference-3d</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\HartsyInference.ThreeD\HartsyInference.ThreeD.csproj" />
    <ProjectReference Include="..\..\src\HartsyInference.Cpu\HartsyInference.Cpu.csproj" />
    <ProjectReference Include="..\..\src\HartsyInference.Cuda\HartsyInference.Cuda.csproj" />
    <ProjectReference Include="..\..\src\HartsyInference.Core\HartsyInference.Core.csproj" />
  </ItemGroup>

</Project>
