<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>SharpInference.Whisper.Cli</RootNamespace>
    <AssemblyName>sharpinference-whisper</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SharpInference.Audio\SharpInference.Audio.csproj" />
    <ProjectReference Include="..\..\src\SharpInference.Cpu\SharpInference.Cpu.csproj" />
    <ProjectReference Include="..\..\src\SharpInference.Core\SharpInference.Core.csproj" />
  </ItemGroup>

</Project>
