using Xunit;
using Xunit.Abstractions;
using HartsyInference.Audio.Models.Codecs.Oobleck;
using HartsyInference.Core.Tensors;
using HartsyInference.Cpu;
using HartsyInference.ModelAssets.SafeTensors;
using HartsyInference.Tests.Common;

namespace HartsyInference.Diffusion.Tests;

/// <summary>Real-weight parity vs diffusers' own <c>AutoencoderOobleck</c> (our downloaded VAE checkpoint IS the
/// diffusers named-submodule layout, so the Python side needs zero key renaming — <c>strict=True</c>
/// <c>load_state_dict</c> succeeds verbatim). Exercises <see cref="OobleckKeyRemap"/>, which translates that
/// named layout into the flat <c>nn.Sequential</c> layout <see cref="OobleckVae"/> expects (the dialect
/// ACE-Step 1.5's checkpoint ships natively). Fixtures generated by
/// <c>tests/python-reference/stable_audio_open_small_parity/gen_vae_reference.py</c> (gitignored <c>*.bin</c>);
/// skip-guarded when either the checkpoint or the fixtures are absent.</summary>
[Trait("Category", "Integration")]
public unsafe class OobleckVaeParityTests
{
    private readonly ITestOutputHelper _output;
    public OobleckVaeParityTests(ITestOutputHelper output) => _output = output;

    [Fact]
    public void Decode_MatchesDiffusersAutoencoderOobleckReference_OnRealWeights()
    {
        string ckptPath = System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
            ".cache", "hartsyinference", "models", "stable-audio-open-small", "vae",
            "diffusion_pytorch_model.safetensors");
        string fixtureDir = System.IO.Path.Combine(RepoRoot.Path, "tests", "python-reference",
            "stable_audio_open_small_parity");

        if (!File.Exists(ckptPath) || !File.Exists(System.IO.Path.Combine(fixtureDir, "vae_pcm_ref.bin")))
        {
            _output.WriteLine("Checkpoint or reference fixtures not present — skipping.");
            return;
        }

        const int LatentT = 4;
        const int Hop = 2048;
        OobleckConfig cfg = OobleckConfig.StableAudioOpen;

        using SafeTensorsLoader loader = new();
        loader.Load(ckptPath);
        Dictionary<string, Tensor> named = loader.GetAllTensors();
        Dictionary<string, Tensor> flat = OobleckKeyRemap.ToFlatSequentialLayout(named, cfg);

        OobleckVae vae = new(cfg);
        vae.LoadWeights(flat);
        using CpuBackend backend = new();

        Tensor latent = ReadBin(System.IO.Path.Combine(fixtureDir, "vae_latent.bin"), new TensorShape(1, cfg.DecoderInputChannels, LatentT));
        Tensor pcm = vae.Decode(backend, latent);
        latent.Dispose();

        Assert.Equal(1, (int)pcm.Shape[0]);
        Assert.Equal(cfg.AudioChannels, (int)pcm.Shape[1]);
        Assert.Equal(LatentT * Hop, (int)pcm.Shape[2]);

        Tensor reference = ReadBin(System.IO.Path.Combine(fixtureDir, "vae_pcm_ref.bin"), new TensorShape(1, cfg.AudioChannels, LatentT * Hop));

        (float cosine, float maxAbsDiff) = Compare(pcm, reference);
        pcm.Dispose();
        reference.Dispose();

        _output.WriteLine($"cosine={cosine:F6} maxAbsDiff={maxAbsDiff:E4}");
        Assert.True(cosine > 0.999f, $"cosine similarity {cosine} too low vs diffusers AutoencoderOobleck reference.");
    }

    private static Tensor ReadBin(string path, TensorShape shape)
    {
        byte[] bytes = File.ReadAllBytes(path);
        Tensor t = new(shape, DType.F32);
        fixed (byte* src = bytes) Buffer.MemoryCopy(src, (void*)t.DataPointer, bytes.Length, bytes.Length);
        return t;
    }

    private static (float Cosine, float MaxAbsDiff) Compare(Tensor a, Tensor b)
    {
        long n = a.Shape.ElementCount;
        float* pa = (float*)a.DataPointer;
        float* pb = (float*)b.DataPointer;
        double dot = 0, na = 0, nb = 0;
        float maxAbsDiff = 0;
        for (long i = 0; i < n; i++)
        {
            dot += (double)pa[i] * pb[i];
            na += (double)pa[i] * pa[i];
            nb += (double)pb[i] * pb[i];
            maxAbsDiff = MathF.Max(maxAbsDiff, MathF.Abs(pa[i] - pb[i]));
        }
        float cosine = (float)(dot / (Math.Sqrt(na) * Math.Sqrt(nb) + 1e-12));
        return (cosine, maxAbsDiff);
    }
}
