using Xunit;
using Xunit.Abstractions;
using HartsyInference.Core.Tensors;
using HartsyInference.Cpu;
using HartsyInference.Diffusion.Models.Denoisers;
using HartsyInference.ModelAssets.SafeTensors;
using HartsyInference.Tests.Common;

namespace HartsyInference.Diffusion.Tests;

/// <summary>Real-weight parity vs the upstream <c>stable_audio_tools.models.dit.DiffusionTransformer</c> (an
/// independent PyTorch library, not diffusers) loaded with the real <c>FastVideo/stable-audio-open-small-Diffusers</c>
/// checkpoint. Fixtures are generated by <c>tests/python-reference/stable_audio_open_small_parity/gen_reference.py</c>
/// (gitignored <c>*.bin</c>) and checked in this repo's fixture directory; skip-guarded when either the checkpoint
/// or the fixtures are absent so this stays out of the no-GPU/no-checkpoint Unit gate.</summary>
[Trait("Category", "Integration")]
public unsafe class StableAudioDitParityTests
{
    private readonly ITestOutputHelper _output;
    public StableAudioDitParityTests(ITestOutputHelper output) => _output = output;

    [Fact]
    public void Forward_MatchesStableAudioToolsReference_OnRealWeights()
    {
        string ckptPath = System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
            ".cache", "hartsyinference", "models", "stable-audio-open-small", "transformer",
            "diffusion_pytorch_model.safetensors");
        string fixtureDir = System.IO.Path.Combine(RepoRoot.Path, "tests", "python-reference",
            "stable_audio_open_small_parity");

        if (!File.Exists(ckptPath) || !File.Exists(System.IO.Path.Combine(fixtureDir, "out_ref.bin")))
        {
            _output.WriteLine("Checkpoint or reference fixtures not present — skipping.");
            return;
        }

        const int T = 8, Lc = 5;
        const float Timestep = 0.37f;
        StableAudioDitConfig cfg = StableAudioDitConfig.OpenSmall;

        using SafeTensorsLoader loader = new();
        loader.Load(ckptPath);
        Dictionary<string, Tensor> weights = loader.GetAllTensors();

        using StableAudioDit dit = new(cfg);
        dit.LoadWeights(weights);
        using CpuBackend backend = new();

        Tensor latent = ReadBin(System.IO.Path.Combine(fixtureDir, "latent.bin"), new TensorShape(1, cfg.IoChannels, T));
        Tensor cond = ReadBin(System.IO.Path.Combine(fixtureDir, "cond.bin"), new TensorShape(1, Lc, cfg.CondTokenDim));
        Tensor globalCond = ReadBin(System.IO.Path.Combine(fixtureDir, "global_embed.bin"), new TensorShape(1, 1, cfg.GlobalCondDim));

        Tensor velocity = dit.Forward(backend, latent, cond, globalCond, Timestep);
        latent.Dispose();
        cond.Dispose();
        globalCond.Dispose();

        Tensor reference = ReadBin(System.IO.Path.Combine(fixtureDir, "out_ref.bin"), new TensorShape(1, cfg.IoChannels, T));

        (float cosine, float maxAbsDiff) = Compare(velocity, reference);
        velocity.Dispose();
        reference.Dispose();

        _output.WriteLine($"cosine={cosine:F6} maxAbsDiff={maxAbsDiff:E4}");
        Assert.True(cosine > 0.999f, $"cosine similarity {cosine} too low vs stable_audio_tools reference.");
    }

    private static Tensor ReadBin(string path, TensorShape shape)
    {
        byte[] bytes = File.ReadAllBytes(path);
        Tensor t = new(shape, DType.F32);
        fixed (byte* src = bytes) Buffer.MemoryCopy(src, (void*)t.DataPointer, bytes.Length, bytes.Length);
        return t;
    }

    private static (float Cosine, float MaxAbsDiff) Compare(Tensor a, Tensor b)
    {
        long n = a.Shape.ElementCount;
        float* pa = (float*)a.DataPointer;
        float* pb = (float*)b.DataPointer;
        double dot = 0, na = 0, nb = 0;
        float maxAbsDiff = 0;
        for (long i = 0; i < n; i++)
        {
            dot += (double)pa[i] * pb[i];
            na += (double)pa[i] * pa[i];
            nb += (double)pb[i] * pb[i];
            maxAbsDiff = MathF.Max(maxAbsDiff, MathF.Abs(pa[i] - pb[i]));
        }
        float cosine = (float)(dot / (Math.Sqrt(na) * Math.Sqrt(nb) + 1e-12));
        return (cosine, maxAbsDiff);
    }
}
