using System.Reflection;
using System.Text.Json;
using Xunit;
using Xunit.Abstractions;
using HartsyInference.Core.Backends;
using HartsyInference.Core.Tensors;
using HartsyInference.Cpu;
using HartsyInference.Diffusion.Models.Denoisers;
using HartsyInference.Diffusion.Models.Denoisers.UNetBlocks;
using HartsyInference.Diffusion.Models.TextEncoders;
using HartsyInference.Diffusion.Schedulers;
using HartsyInference.ModelHandler.SafeTensors;
using HartsyInference.Tests.Common;

namespace HartsyInference.Diffusion.Tests;

/// <summary>
/// Diagnostic tests that instrument the UNet forward pass to capture intermediate tensor
/// statistics at every major layer. Compare results against Python's unet_intermediates.json
/// (generated by dump_layer_outputs.py) to pinpoint where numerical divergence occurs.
/// </summary>
public class UNetDiagnosticTests
{
    private static string ModelDir => TestPaths.Sd15.DiffusersDir;
    private static string DiagnosticsDir => Path.Combine(RepoRoot.Path, "tests", "python-reference");

    private readonly ITestOutputHelper _output;

    public UNetDiagnosticTests(ITestOutputHelper output) => _output = output;

    #region Instrumented UNet Forward Pass

    /// <summary>
    /// Runs a single UNet forward pass using reflection to access internal blocks,
    /// logging tensor stats at every intermediate point. This mirrors the Python
    /// dump_layer_outputs.py script for direct comparison.
    /// </summary>
    [Fact]
    public unsafe void InstrumentedUNetForwardPass()
    {
        if (!Directory.Exists(ModelDir))
        {
            _output.WriteLine($"SKIPPED: Model directory not found: {ModelDir}");
            return;
        }

        // Load UNet
        _output.WriteLine("Loading UNet...");
        UNet unet = new(UNetConfig.Sd15);
        using SafeTensorsLoader unetLoader = new();
        unetLoader.Load(Path.Combine(ModelDir, "unet", "diffusion_pytorch_model.fp16.safetensors"));
        unet.LoadWeights(CastWeightsToF32(unetLoader.GetAllTensors()));

        // Load text encoder for embeddings
        ClipTextEncoderConfig clipConfig = ClipTextEncoderConfig.Sd15;
        ClipTextEncoder textEncoder = new(clipConfig);
        using SafeTensorsLoader teLoader = new();
        teLoader.Load(Path.Combine(ModelDir, "text_encoder", "model.fp16.safetensors"));
        textEncoder.LoadWeights(CastWeightsToF32(teLoader.GetAllTensors()), "text_model");

        using CpuBackend backend = new();

        // Encode negative prompt (unconditional) for a single-pass test
        using HartsyInference.Tokenizers.ClipTokenizer tokenizer = new(
            Path.Combine(ModelDir, "tokenizer", "vocab.json"),
            Path.Combine(ModelDir, "tokenizer", "merges.txt"));
        int[] negativeTokens = tokenizer.Encode("blurry, bad quality");
        Tensor textEmb = textEncoder.Encode(backend, [negativeTokens]);

        // Create step 0 input: noise * InitialNoiseSigma * ScaleModelInput(0) = noise
        EulerDiscreteScheduler scheduler = new();
        scheduler.SetTimesteps(20);
        TensorShape latentShape = new(1, 4, 32, 32);
        Tensor noise = Diffusion.Utilities.SeedGenerator.CreateNoise(latentShape, 42);

        float initSigma = scheduler.InitialNoiseSigma;
        Tensor scaledNoise = new(latentShape, DType.F32);
        backend.Scale(scaledNoise, noise, initSigma);
        noise.Dispose();

        float inputScale = scheduler.ScaleModelInput(0);
        Tensor modelInput;
        if (MathF.Abs(inputScale - 1.0f) > 1e-6f)
        {
            modelInput = new Tensor(latentShape, DType.F32);
            backend.Scale(modelInput, scaledNoise, inputScale);
            scaledNoise.Dispose();
        }
        else
        {
            modelInput = scaledNoise;
        }

        float timestep = 950.0f; // First timestep for 20 steps, leading spacing
        List<(string name, float mean, float std, float min, float max, string shape)> csStats = new();

        void LogStats(string name, Tensor t)
        {
            float mean = ComputeMean(t);
            float std = ComputeStd(t);
            float tMin = ComputeMin(t);
            float tMax = ComputeMax(t);
            string shape = t.Shape.ToString();
            csStats.Add((name, mean, std, tMin, tMax, shape));
        }

        LogStats("unet_input", modelInput);
        LogStats("text_embeddings", textEmb);

        // === Instrumented Forward Pass via Reflection ===
        _output.WriteLine("Running instrumented UNet forward pass...\n");

        int batch = 1;
        int height = (int)modelInput.Shape[2];
        int width = (int)modelInput.Shape[3];
        UNetConfig config = unet.Config;

        // 1. Timestep embedding
        TimestepEmbedding timeEmbedding = GetField<TimestepEmbedding>(unet, "_timeEmbedding");
        Span<float> timesteps = stackalloc float[batch];
        timesteps.Fill(timestep);
        Tensor temb = timeEmbedding.Forward(backend, timesteps, batch);
        LogStats("time_embedding", temb);

        // 2. conv_in
        Tensor convInWeight = GetField<Tensor>(unet, "_convInWeight")!;
        Tensor? convInBias = GetField<Tensor?>(unet, "_convInBias");
        TensorShape convInShape = new(batch, config.ModelChannels, height, width);
        Tensor hidden = new(convInShape, DType.F32);
        backend.Conv2D(hidden, modelInput, convInWeight, convInBias, 1, 1, 1, 1);
        LogStats("conv_in", hidden);

        // 3. Down blocks
        DownBlock[] downBlocks = GetField<DownBlock[]>(unet, "_downBlocks");
        List<Tensor> allSkips = new() { hidden.To(hidden.Device) };

        for (int i = 0; i < downBlocks.Length; i++)
        {
            (Tensor downOut, List<Tensor> skips) = downBlocks[i].Forward(backend, hidden, temb, textEmb);
            hidden.Dispose();
            hidden = downOut;
            allSkips.AddRange(skips);

            LogStats($"down_block_{i}_output", hidden);

            // Log individual skip stats
            for (int j = 0; j < skips.Count; j++)
            {
                LogStats($"down_block_{i}_skip_{j}", skips[j]);
            }
        }

        // 4. Mid block
        UNetResNetBlock midResNet0 = GetField<UNetResNetBlock>(unet, "_midResNet0");
        CrossAttentionBlock midAttention = GetField<CrossAttentionBlock>(unet, "_midAttention");
        UNetResNetBlock midResNet1 = GetField<UNetResNetBlock>(unet, "_midResNet1");

        Tensor midRes0 = midResNet0.Forward(backend, hidden, temb);
        hidden.Dispose();
        LogStats("mid_block.resnets.0", midRes0);

        Tensor midAttn = midAttention.Forward(backend, midRes0, textEmb);
        midRes0.Dispose();
        LogStats("mid_block.attentions.0", midAttn);

        Tensor midRes1 = midResNet1.Forward(backend, midAttn, temb);
        midAttn.Dispose();
        LogStats("mid_block.resnets.1", midRes1);
        hidden = midRes1;

        // 5. Up blocks
        UpBlock[] upBlocks = GetField<UpBlock[]>(unet, "_upBlocks");
        for (int i = 0; i < upBlocks.Length; i++)
        {
            int skipsBefore = allSkips.Count;
            Tensor upOut = upBlocks[i].Forward(backend, hidden, temb, textEmb, allSkips);
            hidden.Dispose();
            hidden = upOut;
            int skipsConsumed = skipsBefore - allSkips.Count;
            LogStats($"up_block_{i}_output", hidden);
        }

        temb.Dispose();

        // 6. Final conv_norm_out → SiLU → conv_out
        Tensor normOutWeight = GetField<Tensor>(unet, "_normOutWeight")!;
        Tensor normOutBias = GetField<Tensor>(unet, "_normOutBias")!;
        Tensor convOutWeight = GetField<Tensor>(unet, "_convOutWeight")!;
        Tensor? convOutBias = GetField<Tensor?>(unet, "_convOutBias");

        int finalH = (int)hidden.Shape[2];
        int finalW = (int)hidden.Shape[3];
        int finalCh = config.ModelChannels;

        TensorShape finalShape = new(batch, finalCh, finalH, finalW);
        Tensor normOut = new(finalShape, DType.F32);
        backend.GroupNorm(normOut, hidden, normOutWeight, normOutBias, config.NormNumGroups, config.NormEps);
        hidden.Dispose();
        LogStats("conv_norm_out", normOut);

        Tensor siluOut = new(finalShape, DType.F32);
        backend.Silu(siluOut, normOut);
        normOut.Dispose();

        TensorShape outShape = new(batch, config.OutChannels, finalH, finalW);
        Tensor output = new(outShape, DType.F32);
        backend.Conv2D(output, siluOut, convOutWeight, convOutBias, 1, 1, 1, 1);
        siluOut.Dispose();
        LogStats("conv_out", output);
        LogStats("unet_output", output);

        // === Print results ===
        _output.WriteLine($"{"Layer",-40} {"Shape",-20} {"Mean",12} {"Std",12} {"Min",12} {"Max",12}");
        _output.WriteLine(new string('-', 108));
        foreach ((string name, float mean, float std, float min, float max, string shape) in csStats)
        {
            _output.WriteLine($"{name,-40} {shape,-20} {mean,12:F5} {std,12:F5} {min,12:F5} {max,12:F5}");
        }

        // === Compare against Python reference if available ===
        string pyIntermediatesPath = Path.Combine(DiagnosticsDir, "unet_intermediates.json");
        if (File.Exists(pyIntermediatesPath))
        {
            _output.WriteLine("\n\n=== Python Comparison ===");
            ComparePythonIntermediates(pyIntermediatesPath, csStats);
        }
        else
        {
            _output.WriteLine($"\nTo compare against Python, run: python tests/python-reference/dump_layer_outputs.py");
        }

        // Cleanup
        output.Dispose();
        modelInput.Dispose();
        textEmb.Dispose();
        foreach (Tensor skip in allSkips) skip.Dispose();
    }

    #endregion

    #region CFG Guidance Effectiveness Test

    /// <summary>
    /// Tests whether classifier-free guidance is producing meaningful conditioning by comparing
    /// unconditional and conditional noise predictions. If cond ≈ uncond, CFG is ineffective
    /// and images will be flat/featureless regardless of prompt.
    /// </summary>
    [Fact]
    public unsafe void CfgGuidanceEffectiveness()
    {
        if (!Directory.Exists(ModelDir))
        {
            _output.WriteLine($"SKIPPED: Model directory not found: {ModelDir}");
            return;
        }

        _output.WriteLine("Loading models...");
        using CpuBackend backend = new();

        // Load text encoder
        ClipTextEncoderConfig clipConfig = ClipTextEncoderConfig.Sd15;
        ClipTextEncoder textEncoder = new(clipConfig);
        using SafeTensorsLoader teLoader = new();
        teLoader.Load(Path.Combine(ModelDir, "text_encoder", "model.fp16.safetensors"));
        textEncoder.LoadWeights(CastWeightsToF32(teLoader.GetAllTensors()), "text_model");

        // Load UNet
        UNet unet = new(UNetConfig.Sd15);
        using SafeTensorsLoader unetLoader = new();
        unetLoader.Load(Path.Combine(ModelDir, "unet", "diffusion_pytorch_model.fp16.safetensors"));
        unet.LoadWeights(CastWeightsToF32(unetLoader.GetAllTensors()));

        // Encode both negative and positive prompts
        using HartsyInference.Tokenizers.ClipTokenizer tokenizer = new(
            Path.Combine(ModelDir, "tokenizer", "vocab.json"),
            Path.Combine(ModelDir, "tokenizer", "merges.txt"));

        int[] promptTokens = tokenizer.Encode("a painting of a cat sitting on a windowsill");
        int[] negativeTokens = tokenizer.Encode("blurry, bad quality");

        // Encode separately to see individual stats
        Tensor negEmb = textEncoder.Encode(backend, [negativeTokens]);
        Tensor posEmb = textEncoder.Encode(backend, [promptTokens]);

        _output.WriteLine($"\nText embedding stats:");
        _output.WriteLine($"  Negative: mean={ComputeMean(negEmb):F6}, std={ComputeStd(negEmb):F6}");
        _output.WriteLine($"  Positive: mean={ComputeMean(posEmb):F6}, std={ComputeStd(posEmb):F6}");

        // Compute embedding difference
        float embDiffMean = 0, embDiffStd = 0;
        {
            float* negPtr = (float*)negEmb.DataPointer;
            float* posPtr = (float*)posEmb.DataPointer;
            long count = negEmb.ElementCount;
            double sum = 0, sumSq = 0;
            for (long i = 0; i < count; i++)
            {
                double diff = posPtr[i] - negPtr[i];
                sum += diff;
                sumSq += diff * diff;
            }
            embDiffMean = (float)(sum / count);
            embDiffStd = (float)Math.Sqrt(sumSq / count - (sum / count) * (sum / count));
        }
        _output.WriteLine($"  Difference (pos-neg): mean={embDiffMean:F6}, std={embDiffStd:F6}");

        // Create step 0 input
        TensorShape latentShape = new(1, 4, 32, 32);
        Tensor noise = Diffusion.Utilities.SeedGenerator.CreateNoise(latentShape, 42);
        float timestep = 950.0f;

        _output.WriteLine($"\nRunning UNet passes at t={timestep}...");

        // Unconditional pass
        Tensor uncondPred = unet.Forward(backend, noise, timestep, negEmb);
        float uncondMean = ComputeMean(uncondPred);
        float uncondStd = ComputeStd(uncondPred);

        // Conditional pass
        Tensor condPred = unet.Forward(backend, noise, timestep, posEmb);
        float condMean = ComputeMean(condPred);
        float condStd = ComputeStd(condPred);

        _output.WriteLine($"\nUNet noise predictions:");
        _output.WriteLine($"  Uncond: mean={uncondMean:F6}, std={uncondStd:F6}");
        _output.WriteLine($"  Cond:   mean={condMean:F6}, std={condStd:F6}");

        // Compute prediction difference (what CFG amplifies)
        float* uncPtr = (float*)uncondPred.DataPointer;
        float* conPtr = (float*)condPred.DataPointer;
        int count2 = (int)latentShape.ElementCount;

        double diffSum = 0, diffSumSq = 0, diffAbsSum = 0;
        float maxDiff = 0;
        for (int i = 0; i < count2; i++)
        {
            float diff = conPtr[i] - uncPtr[i];
            diffSum += diff;
            diffSumSq += (double)diff * diff;
            diffAbsSum += MathF.Abs(diff);
            if (MathF.Abs(diff) > MathF.Abs(maxDiff)) maxDiff = diff;
        }
        float diffMean = (float)(diffSum / count2);
        float diffStd = (float)Math.Sqrt(diffSumSq / count2 - (diffSum / count2) * (diffSum / count2));
        float diffAbsMean = (float)(diffAbsSum / count2);

        _output.WriteLine($"\nCond - Uncond difference (what CFG amplifies by 7.5x):");
        _output.WriteLine($"  Mean: {diffMean:F6}");
        _output.WriteLine($"  Std:  {diffStd:F6}");
        _output.WriteLine($"  Abs mean: {diffAbsMean:F6}");
        _output.WriteLine($"  Max abs: {MathF.Abs(maxDiff):F6}");

        // CFG output: uncond + 7.5 * (cond - uncond)
        float cfgScale = 7.5f;
        double cfgSum = 0, cfgSumSq = 0;
        for (int i = 0; i < count2; i++)
        {
            float cfgVal = uncPtr[i] + cfgScale * (conPtr[i] - uncPtr[i]);
            cfgSum += cfgVal;
            cfgSumSq += (double)cfgVal * cfgVal;
        }
        float cfgMean = (float)(cfgSum / count2);
        float cfgStd = (float)Math.Sqrt(cfgSumSq / count2 - (cfgSum / count2) * (cfgSum / count2));

        _output.WriteLine($"\nCFG output (uncond + 7.5*(cond-uncond)):");
        _output.WriteLine($"  Mean: {cfgMean:F6}");
        _output.WriteLine($"  Std:  {cfgStd:F6}");

        // Python reference for comparison
        _output.WriteLine($"\nPython reference (from reference_stats.json):");
        _output.WriteLine($"  step0_noise_pred_uncond: mean=-0.003, std=0.996");
        _output.WriteLine($"  step0_noise_pred_cond:   mean=-0.004, std=0.997");

        // Verdict
        _output.WriteLine($"\n=== CFG Verdict ===");
        float condUncondRatio = diffStd / uncondStd;
        _output.WriteLine($"  cond-uncond std / uncond std = {condUncondRatio:F4}");

        if (diffStd < 0.001f)
        {
            _output.WriteLine("  PROBLEM: Cond and uncond predictions are nearly identical!");
            _output.WriteLine("  CFG guidance is NOT working. Cross-attention or text encoder has a bug.");
        }
        else if (diffStd < 0.01f)
        {
            _output.WriteLine("  WARNING: Cond-uncond difference is very small. Guidance signal may be weak.");
        }
        else
        {
            _output.WriteLine("  OK: Meaningful difference between cond and uncond predictions.");
            _output.WriteLine($"  The CFG guidance signal has std={diffStd:F6}, amplified to {diffStd * cfgScale:F6} by CFG.");
        }

        uncondPred.Dispose();
        condPred.Dispose();
        noise.Dispose();
        negEmb.Dispose();
        posEmb.Dispose();
    }

    #endregion

    #region Quick UNet Sanity Check

    /// <summary>
    /// Runs a single UNet forward pass (no instrumentation) and checks that the output
    /// has reasonable statistics for epsilon prediction (mean near 0, std near 1).
    /// Does NOT require Python reference data.
    /// </summary>
    [Fact]
    public void UNetOutputSanityCheck()
    {
        if (!Directory.Exists(ModelDir))
        {
            _output.WriteLine($"SKIPPED: Model directory not found: {ModelDir}");
            return;
        }

        _output.WriteLine("Loading model...");
        UNet unet = new(UNetConfig.Sd15);
        using SafeTensorsLoader unetLoader = new();
        unetLoader.Load(Path.Combine(ModelDir, "unet", "diffusion_pytorch_model.fp16.safetensors"));
        unet.LoadWeights(CastWeightsToF32(unetLoader.GetAllTensors()));

        using CpuBackend backend = new();

        // Create a simple input: random noise as latent, zeros as text embedding
        TensorShape latentShape = new(1, 4, 32, 32);
        Tensor latent = Diffusion.Utilities.SeedGenerator.CreateNoise(latentShape, 42);

        // Simple zero text embedding [1, 77, 768]
        TensorShape embShape = new(1, 77, 768);
        Tensor textEmb = new(embShape, DType.F32);

        _output.WriteLine($"Input: mean={ComputeMean(latent):F6}, std={ComputeStd(latent):F6}");

        Tensor output = unet.Forward(backend, latent, 999.0f, textEmb);

        float outMean = ComputeMean(output);
        float outStd = ComputeStd(output);
        _output.WriteLine($"Output (t=999): mean={outMean:F6}, std={outStd:F6}");

        // For epsilon prediction at t=999 (high noise), the UNet should predict noise-like output
        // Mean should be near 0, std should be roughly order of magnitude 1
        _output.WriteLine($"\nSanity checks:");
        _output.WriteLine($"  |mean| < 1.0: {MathF.Abs(outMean) < 1.0f}");
        _output.WriteLine($"  0.01 < std < 10.0: {outStd > 0.01f && outStd < 10.0f}");
        _output.WriteLine($"  No NaN: {!float.IsNaN(outMean)}");
        _output.WriteLine($"  No Inf: {!float.IsInfinity(outStd)}");

        Assert.False(float.IsNaN(outMean), "UNet output contains NaN");
        Assert.False(float.IsInfinity(outStd), "UNet output contains Inf");
        Assert.True(outStd > 0.01f, $"UNet output std is too small: {outStd}");
        Assert.True(outStd < 10.0f, $"UNet output std is too large: {outStd}");

        output.Dispose();
        latent.Dispose();
        textEmb.Dispose();
    }

    #endregion

    #region Python Comparison

    private void ComparePythonIntermediates(
        string jsonPath,
        List<(string name, float mean, float std, float min, float max, string shape)> csStats)
    {
        string json = File.ReadAllText(jsonPath);
        List<Dictionary<string, JsonElement>>? pyStats =
            JsonSerializer.Deserialize<List<Dictionary<string, JsonElement>>>(json);

        if (pyStats == null)
        {
            _output.WriteLine("Failed to parse Python intermediates JSON.");
            return;
        }

        // Build lookup from Python stats
        Dictionary<string, (double mean, double std, double min, double max)> pyLookup = new();
        foreach (Dictionary<string, JsonElement> entry in pyStats)
        {
            if (!entry.TryGetValue("name", out JsonElement nameEl)) continue;
            string? name = nameEl.GetString();
            if (name == null || !entry.ContainsKey("mean")) continue;

            pyLookup[name] = (
                entry["mean"].GetDouble(),
                entry["std"].GetDouble(),
                entry["min"].GetDouble(),
                entry["max"].GetDouble()
            );
        }

        // Map C# names to Python hook names for comparison
        Dictionary<string, string> nameMap = BuildNameMap();

        _output.WriteLine($"\n{"C# Layer",-40} {"C# Std",10} {"Py Std",10} {"Ratio",10} {"Match?",8}");
        _output.WriteLine(new string('-', 80));

        foreach ((string name, float mean, float std, float min, float max, string shape) in csStats)
        {
            // Try direct name match or mapped name
            string pyName = nameMap.TryGetValue(name, out string? mapped) ? mapped : name;

            if (pyLookup.TryGetValue(pyName, out (double mean, double std, double min, double max) py))
            {
                double ratio = std / py.std;
                bool match = Math.Abs(ratio - 1.0) < 0.05; // Within 5%
                string matchStr = match ? "OK" : "DIVERGE";
                _output.WriteLine($"{name,-40} {std,10:F5} {py.std,10:F5} {ratio,10:F4} {matchStr,8}");

                if (!match)
                {
                    _output.WriteLine($"  ** MISMATCH: C# mean={mean:F5} vs Py mean={py.mean:F5}");
                    _output.WriteLine($"  ** MISMATCH: C# std={std:F5} vs Py std={py.std:F5}");
                }
            }
        }
    }

    /// <summary>Maps C# intermediate names to Python forward hook names.</summary>
    private static Dictionary<string, string> BuildNameMap()
    {
        Dictionary<string, string> map = new()
        {
            ["unet_input"] = "unet_input",
            ["text_embeddings"] = "text_embeddings",
            ["time_embedding"] = "time_embedding",
            ["conv_in"] = "conv_in",
            ["mid_block.resnets.0"] = "mid_block.resnets.0",
            ["mid_block.attentions.0"] = "mid_block.attentions.0",
            ["mid_block.resnets.1"] = "mid_block.resnets.1",
            ["conv_norm_out"] = "conv_norm_out",
            ["conv_out"] = "conv_out",
            ["unet_output"] = "unet_output",
        };

        // Down blocks: C# "down_block_0_output" -> Python hook captures resnets/attentions individually
        // The Python hooks capture each resnet and attention output separately
        // C# captures the block output (after downsample if present)
        for (int i = 0; i < 4; i++)
        {
            // Map up block outputs
            map[$"up_block_{i}_output"] = $"up_blocks.{i}.upsamplers.0"; // Last op is upsample (except block 0 which has no upsample)
        }

        return map;
    }

    #endregion

    #region Layer-by-Layer Comparison with Python Reference

    /// <summary>
    /// Runs C# UNet layer-by-layer using Python's exact input tensors and compares
    /// each layer's output element-wise against Python reference binaries.
    /// This isolates the FIRST layer where significant divergence appears.
    /// </summary>
    [Fact]
    public unsafe void LayerByLayerComparisonWithPythonInputs()
    {
        string layersDir = Path.Combine(DiagnosticsDir, "reference_tensors", "layers");
        string refDir = Path.Combine(DiagnosticsDir, "reference_tensors");

        if (!File.Exists(Path.Combine(layersDir, "index.json")))
        {
            _output.WriteLine("SKIPPED: Layer reference not found. Run dump_layer_outputs.py first.");
            return;
        }
        if (!Directory.Exists(ModelDir))
        {
            _output.WriteLine($"SKIPPED: Model directory not found: {ModelDir}");
            return;
        }

        using CpuBackend backend = new();

        // Load UNet weights
        UNet unet = new(UNetConfig.Sd15);
        using SafeTensorsLoader unetLoader = new();
        unetLoader.Load(Path.Combine(ModelDir, "unet", "diffusion_pytorch_model.fp16.safetensors"));
        Dictionary<string, Tensor> weights = CastWeightsToF32(unetLoader.GetAllTensors());
        unet.LoadWeights(weights);

        // Load Python's exact input tensors
        TensorShape latentShape = new(1, 4, 32, 32);
        Tensor input = LoadBinaryTensor(Path.Combine(refDir, "unet_step0_input.bin"), latentShape);
        TensorShape embShape = new(1, 77, 768);
        Tensor textEmb = LoadBinaryTensor(Path.Combine(refDir, "unet_step0_text_emb.bin"), embShape);

        _output.WriteLine($"Input: mean={ComputeMean(input):F6}, std={ComputeStd(input):F6}");
        _output.WriteLine($"TextEmb: mean={ComputeMean(textEmb):F6}, std={ComputeStd(textEmb):F6}");

        float timestep = 950.0f;

        // Run individual layers manually using reflection to access private fields
        // 1. Time embedding
        TimestepEmbedding timeEmb = GetField<TimestepEmbedding>(unet, "_timeEmbedding");
        Span<float> timesteps = stackalloc float[1];
        timesteps[0] = timestep;
        Tensor temb = timeEmb.Forward(backend, timesteps, 1);
        CompareWithReference(layersDir, "time_embedding", temb, new TensorShape(1, 1280));

        // 2. Conv_in
        Tensor convInWeight = GetField<Tensor>(unet, "_convInWeight")!;
        Tensor convInBias = GetField<Tensor>(unet, "_convInBias")!;
        TensorShape convInOutShape = new(1, 320, 32, 32);
        Tensor hidden = new(convInOutShape, DType.F32);
        backend.Conv2D(hidden, input, convInWeight, convInBias, 1, 1, 1, 1);
        CompareWithReference(layersDir, "conv_in", hidden, convInOutShape);

        // 3. Run down blocks layer-by-layer with per-sublayer comparison
        DownBlock[] downBlocks = GetField<DownBlock[]>(unet, "_downBlocks");
        List<Tensor> allSkips = new() { hidden.To(hidden.Device) };

        _output.WriteLine("\n--- Down Blocks (manual sub-layer execution) ---");
        for (int bi = 0; bi < downBlocks.Length; bi++)
        {
            DownBlock db = downBlocks[bi];
            UNetResNetBlock[] resnets = GetField<UNetResNetBlock[]>(db, "_resnets");
            CrossAttentionBlock?[] attentions = GetField<CrossAttentionBlock?[]>(db, "_attentions");
            int numLayers = GetField<int>(db, "_numLayers");
            bool hasAttention = GetField<bool>(db, "_hasAttention");
            bool hasDownsample = GetField<bool>(db, "_hasDownsample");

            for (int li = 0; li < numLayers; li++)
            {
                Tensor resOut = resnets[li].Forward(backend, hidden, temb);
                if (li > 0 || bi > 0) hidden.Dispose();
                hidden = resOut;
                CompareWithReference(layersDir, $"down_blocks.{bi}.resnets.{li}", hidden, hidden.Shape);

                if (hasAttention && attentions[li] is not null)
                {
                    Tensor attnOut = attentions[li]!.Forward(backend, hidden, textEmb);
                    hidden.Dispose();
                    hidden = attnOut;
                    CompareWithReference(layersDir, $"down_blocks.{bi}.attentions.{li}", hidden, hidden.Shape);
                }

                allSkips.Add(hidden.To(hidden.Device));
            }

            if (hasDownsample)
            {
                Tensor dsWeight = GetField<Tensor>(db, "_downsampleWeight")!;
                Tensor dsBias = GetField<Tensor>(db, "_downsampleBias")!;
                int batch2 = (int)hidden.Shape[0];
                int ch = (int)hidden.Shape[1];
                int h2 = (int)hidden.Shape[2];
                int w2 = (int)hidden.Shape[3];
                TensorShape dsShape = new(batch2, ch, h2 / 2, w2 / 2);
                Tensor downsampled = new(dsShape, DType.F32);
                backend.Conv2D(downsampled, hidden, dsWeight, dsBias, 2, 2, 1, 1);
                hidden.Dispose();
                hidden = downsampled;
                CompareWithReference(layersDir, $"down_blocks.{bi}.downsamplers.0", hidden, hidden.Shape);
                allSkips.Add(hidden.To(hidden.Device));
            }
        }

        _output.WriteLine("\n--- Mid Block ---");

        // 4. Mid block
        UNetResNetBlock midResNet0 = GetField<UNetResNetBlock>(unet, "_midResNet0");
        CrossAttentionBlock midAttn = GetField<CrossAttentionBlock>(unet, "_midAttention");
        UNetResNetBlock midResNet1 = GetField<UNetResNetBlock>(unet, "_midResNet1");

        Tensor midRes0Out = midResNet0.Forward(backend, hidden, temb);
        hidden.Dispose();
        CompareWithReference(layersDir, "mid_block.resnets.0", midRes0Out, midRes0Out.Shape);

        Tensor midAttnOut = midAttn.Forward(backend, midRes0Out, textEmb);
        midRes0Out.Dispose();
        CompareWithReference(layersDir, "mid_block.attentions.0", midAttnOut, midAttnOut.Shape);

        Tensor midRes1Out = midResNet1.Forward(backend, midAttnOut, temb);
        midAttnOut.Dispose();
        CompareWithReference(layersDir, "mid_block.resnets.1", midRes1Out, midRes1Out.Shape);

        hidden = midRes1Out;

        // 5. Up blocks
        UpBlock[] upBlocks = GetField<UpBlock[]>(unet, "_upBlocks");
        for (int i = 0; i < upBlocks.Length; i++)
        {
            Tensor upOut = upBlocks[i].Forward(backend, hidden, temb, textEmb, allSkips);
            hidden.Dispose();
            hidden = upOut;
        }

        // 6. Final layers
        Tensor normOutWeight = GetField<Tensor>(unet, "_normOutWeight")!;
        Tensor normOutBias = GetField<Tensor>(unet, "_normOutBias")!;
        Tensor convOutWeight = GetField<Tensor>(unet, "_convOutWeight")!;
        Tensor convOutBias = GetField<Tensor>(unet, "_convOutBias")!;

        int finalH = (int)hidden.Shape[2];
        int finalW = (int)hidden.Shape[3];
        int finalCh = 320;

        TensorShape finalShape = new(1, finalCh, finalH, finalW);
        Tensor normOut = new(finalShape, DType.F32);
        backend.GroupNorm(normOut, hidden, normOutWeight, normOutBias, 32, 1e-6f);
        hidden.Dispose();
        CompareWithReference(layersDir, "conv_norm_out", normOut, finalShape);

        Tensor siluOut = new(finalShape, DType.F32);
        backend.Silu(siluOut, normOut);
        normOut.Dispose();

        TensorShape outShape = new(1, 4, finalH, finalW);
        Tensor output = new(outShape, DType.F32);
        backend.Conv2D(output, siluOut, convOutWeight, convOutBias, 1, 1, 1, 1);
        siluOut.Dispose();
        CompareWithReference(layersDir, "conv_out", output, outShape);

        _output.WriteLine($"\nFinal output: mean={ComputeMean(output):F6}, std={ComputeStd(output):F6}");

        // Cleanup
        temb.Dispose();
        input.Dispose();
        textEmb.Dispose();
        output.Dispose();
        foreach (Tensor skip in allSkips) skip.Dispose();
    }

    private unsafe void CompareWithReference(string layersDir, string layerName, Tensor csTensor, TensorShape expectedShape)
    {
        string fileName = layerName.Replace(".", "_") + ".bin";
        string refPath = Path.Combine(layersDir, fileName);

        if (!File.Exists(refPath))
        {
            _output.WriteLine($"  {layerName}: NO REFERENCE FILE ({fileName})");
            return;
        }

        Tensor pyTensor = LoadBinaryTensor(refPath, expectedShape);
        float* csPtr = (float*)csTensor.DataPointer;
        float* pyPtr = (float*)pyTensor.DataPointer;
        int count = (int)expectedShape.ElementCount;

        float maxAbsErr = 0f;
        double sumAbsErr = 0;
        int maxErrIdx = 0;

        for (int i = 0; i < count; i++)
        {
            float err = MathF.Abs(csPtr[i] - pyPtr[i]);
            sumAbsErr += err;
            if (err > maxAbsErr)
            {
                maxAbsErr = err;
                maxErrIdx = i;
            }
        }

        double avgAbsErr = sumAbsErr / count;
        float csMean = ComputeMean(csTensor);
        float csStd = ComputeStd(csTensor);
        float pyMean = ComputeMean(pyTensor);
        float pyStd = ComputeStd(pyTensor);

        string marker = avgAbsErr > 0.01 ? " <<<" : "";
        _output.WriteLine($"  {layerName,-40} avg_err={avgAbsErr:E3} max_err={maxAbsErr:E3} cs_std={csStd:F4} py_std={pyStd:F4}{marker}");

        if (avgAbsErr > 0.01)
        {
            _output.WriteLine($"    DIVERGENCE: C# val[{maxErrIdx}]={csPtr[maxErrIdx]:F6}, Py val[{maxErrIdx}]={pyPtr[maxErrIdx]:F6}");
            _output.WriteLine($"    C# mean={csMean:F6}, Py mean={pyMean:F6}");
        }

        pyTensor.Dispose();
    }

    private static unsafe Tensor LoadBinaryTensor(string path, TensorShape shape)
    {
        byte[] bytes = File.ReadAllBytes(path);
        long expectedBytes = shape.ElementCount * sizeof(float);
        if (bytes.Length != expectedBytes)
            throw new InvalidOperationException(
                $"Binary tensor size mismatch for {path}: got {bytes.Length} bytes, expected {expectedBytes} for shape {shape}");

        Tensor tensor = new(shape, DType.F32);
        fixed (byte* src = bytes)
        {
            Buffer.MemoryCopy(src, (void*)tensor.DataPointer, expectedBytes, expectedBytes);
        }
        return tensor;
    }

    #endregion

    #region Helpers

    private static T GetField<T>(object obj, string fieldName)
    {
        FieldInfo? field = obj.GetType().GetField(fieldName, BindingFlags.NonPublic | BindingFlags.Instance);
        if (field == null) throw new InvalidOperationException($"Field '{fieldName}' not found on {obj.GetType().Name}");
        return (T)field.GetValue(obj)!;
    }

    private static unsafe float ComputeMean(Tensor tensor)
    {
        float* ptr = (float*)tensor.DataPointer;
        long count = tensor.ElementCount;
        double sum = 0;
        for (long i = 0; i < count; i++) sum += ptr[i];
        return (float)(sum / count);
    }

    private static unsafe float ComputeStd(Tensor tensor)
    {
        float* ptr = (float*)tensor.DataPointer;
        long count = tensor.ElementCount;
        double sum = 0, sumSq = 0;
        for (long i = 0; i < count; i++)
        {
            sum += ptr[i];
            sumSq += (double)ptr[i] * ptr[i];
        }
        double mean = sum / count;
        return (float)Math.Sqrt(Math.Max(0, sumSq / count - mean * mean));
    }

    private static unsafe float ComputeMin(Tensor tensor)
    {
        float* ptr = (float*)tensor.DataPointer;
        long count = tensor.ElementCount;
        float min = float.MaxValue;
        for (long i = 0; i < count; i++)
            if (ptr[i] < min) min = ptr[i];
        return min;
    }

    private static unsafe float ComputeMax(Tensor tensor)
    {
        float* ptr = (float*)tensor.DataPointer;
        long count = tensor.ElementCount;
        float max = float.MinValue;
        for (long i = 0; i < count; i++)
            if (ptr[i] > max) max = ptr[i];
        return max;
    }

    private static Dictionary<string, Tensor> CastWeightsToF32(Dictionary<string, Tensor> weights)
    {
        Dictionary<string, Tensor> f32 = new(weights.Count);
        foreach (KeyValuePair<string, Tensor> kvp in weights)
        {
            f32[kvp.Key] = (kvp.Value.DType == DType.F16 || kvp.Value.DType == DType.BF16)
                ? kvp.Value.CastTo(DType.F32)
                : kvp.Value;
        }
        return f32;
    }

    #endregion
}
