using System.Numerics;

namespace HartsyInference.Audio.Dsp;

/// <summary>The one xorshift32 + Box-Muller generator every audio model's deterministic noise path shares. A
/// 32-bit state, a fixed seeding rule and a fixed sample order are what make a model's noise reproducible
/// across runs and across streaming chunk boundaries.</summary>
public static class DeterministicRng
{
    /// <summary>Derives a non-zero state from an integer seed (the seeding convention every model used).</summary>
    public static uint Seed(int seed) => unchecked((uint)seed * 2654435761u + 0x9E3779B9u) | 1u;

    /// <summary>Advances the state and returns a uniform sample in <c>[0, 1)</c> with 24-bit resolution.</summary>
    public static float NextUniform(ref uint state)
    {
        state = Step(state);
        return (state & 0xFFFFFF) / 16777216f;
    }

    /// <summary>Advances the state twice and returns one standard-normal sample via Box-Muller.</summary>
    public static float NextGaussian(ref uint state)
    {
        float u1 = NextUniform(ref state);
        float u2 = NextUniform(ref state);
        if (u1 < 1e-7f) u1 = 1e-7f;
        return MathF.Sqrt(-2f * MathF.Log(u1)) * MathF.Cos(2f * MathF.PI * u2);
    }

    /// <summary>The state after <paramref name="steps"/> calls to <see cref="NextUniform"/>, without walking them.
    /// The xorshift step is a linear map over GF(2)^32, so its <paramref name="steps"/>-th power is a 32-column bit
    /// matrix built by square-and-multiply; this is what lets one noise sequence be generated by several workers,
    /// each starting at its own offset, and still be bit-identical to the sequential walk.</summary>
    public static uint Advance(uint state, long steps)
    {
        if (steps < 0) throw new ArgumentOutOfRangeException(nameof(steps));
        if (steps == 0) return state;
        Span<uint> power = stackalloc uint[32];
        Span<uint> result = stackalloc uint[32];
        Span<uint> scratch = stackalloc uint[32];
        for (int j = 0; j < 32; j++)
        {
            uint basis = 1u << j;
            power[j] = Step(basis);
            result[j] = basis;
        }
        long remaining = steps;
        while (remaining > 0)
        {
            if ((remaining & 1) != 0)
            {
                Compose(power, result, scratch);
                scratch.CopyTo(result);
            }
            remaining >>= 1;
            if (remaining > 0)
            {
                Compose(power, power, scratch);
                scratch.CopyTo(power);
            }
        }
        return Apply(result, state);
    }

    private static uint Step(uint x)
    {
        x ^= x << 13;
        x ^= x >> 17;
        x ^= x << 5;
        return x;
    }

    /// <summary><c>columns · v</c> over GF(2): XOR of the columns selected by the set bits of <paramref name="v"/>.</summary>
    private static uint Apply(ReadOnlySpan<uint> columns, uint v)
    {
        uint result = 0;
        while (v != 0)
        {
            result ^= columns[BitOperations.TrailingZeroCount(v)];
            v &= v - 1;
        }
        return result;
    }

    /// <summary><c>output = a ∘ b</c> in column form: column j of the product is <c>a</c> applied to column j of <c>b</c>.</summary>
    private static void Compose(ReadOnlySpan<uint> a, ReadOnlySpan<uint> b, Span<uint> output)
    {
        for (int j = 0; j < 32; j++) output[j] = Apply(a, b[j]);
    }
}
